
import { VehicleInspectionIntervals } from "./vehicleinspectionintervals.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
@Injectable()
export class VehicleInspectionIntervalsService extends TypeOrmCrudService<VehicleInspectionIntervals> {
  constructor(@InjectRepository(VehicleInspectionIntervals) repo) {
    super(repo);
  }

  public async createDTO(dto: any) {
    await this.repo.save(dto);
  }

  async deleteByParentId(parentId){
    if(!parentId || parentId <= -1) {
      throw new Error("you must provide an valid user group id in deleteByParentId");
    }

    await this.repo.createQueryBuilder()
    .delete()
    .from(VehicleInspectionIntervals)
    .where("vehicleDetailId = :id", { id: parentId })
    .execute();
  }
}
