
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { VehicleInspectionIntervals } from './vehicleinspectionintervals.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VehicleInspectionIntervalsService } from './vehicleinspectionintervals.service';
import { VehicleInspectionIntervalsController } from './vehicleinspectionintervals.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([VehicleInspectionIntervals]), AuthModule],
    providers: [VehicleInspectionIntervalsService],
    exports: [],
    controllers: [VehicleInspectionIntervalsController],
  })
  export class VehicleInspectionIntervalsModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('vehicleinspectionintervals');
    }
  }
