

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Mar 03 2021 16:14:59 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { FileSystem } from './file-system.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FileSystemService } from './file-system.service';
import { FileSystemController } from './file-system.controller';

@Module({
    imports: [TypeOrmModule.forFeature([FileSystem])],
    providers: [FileSystemService],
    exports: [],
    controllers: [FileSystemController],
  })
  export class FileSystemModule {}

