
import { FileSystem } from "./file-system.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { FileSystemService } from "./file-system.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Mar 03 2021 16:14:59 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: FileSystem
    }
  })
  @Controller('file-system')
  export class FileSystemController implements CrudController<FileSystem> {
    constructor(public service: FileSystemService) {}
  }
