
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Mar 03 2021 16:14:59 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class FileSystem {
  @PrimaryGeneratedColumn() id: number;
  @Column() folderName: string = '';
  @Column({type:'text'}) description: string = '';
  @Column({nullable:true,default:1}) parentId: number = 1;
  @Column() createdBy: number = -1;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
