

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Mar 09 2021 13:12:02 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { ShreddingMethod } from './shredding-method.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ShreddingMethodService } from './shredding-method.service';
import { ShreddingMethodController } from './shredding-method.controller';

@Module({
    imports: [TypeOrmModule.forFeature([ShreddingMethod])],
    providers: [ShreddingMethodService],
    exports: [],
    controllers: [ShreddingMethodController],
  })
  export class ShreddingMethodModule {}

