
import { ShreddingMethod } from "./shredding-method.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ShreddingMethodService } from "./shredding-method.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Mar 09 2021 13:12:02 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: ShreddingMethod
    }
  })
  @Controller('shredding-method')
  export class ShreddingMethodController implements CrudController<ShreddingMethod> {
    constructor(public service: ShreddingMethodService) {}
  }
