

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 05 2020 14:08:07 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { TipDetails } from './tip-details.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TipDetailsService } from './tip-details.service';
import { TipDetailsController } from './tip-details.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TipDetails])],
    providers: [TipDetailsService],
    exports: [],
    controllers: [TipDetailsController],
  })
  export class TipDetailsModule {}

