
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 05 2020 14:08:07 GMT+0100 (British Summer Time)
 */
@Entity()
export class TipDetails {
  @PrimaryGeneratedColumn() id: number;

  @Column() tipId: number = -1;

  @Column() licenceNumber: string = '';
  @Column() carrierLicenceNumber: string = '';
  @Column() carrierLicenceExpiryDate: string = ''; 

  @Column() ewcCodes: string = '';

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
