
import { TipDetails } from "./tip-details.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 05 2020 14:08:07 GMT+0100 (British Summer Time)
 */
@Injectable()
export class TipDetailsService extends TypeOrmCrudService<TipDetails> {
  constructor(@InjectRepository(TipDetails) repo) {
    super(repo);
  }
}
