
import { PartCategory } from "./part-category.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 29 2021 11:51:09 GMT+0100 (British Summer Time)
 */
@Injectable()
export class PartCategoryService extends TypeOrmCrudService<PartCategory> {
  constructor(@InjectRepository(PartCategory) repo) {
    super(repo);
  }
}
