
import { PartCategory } from "./part-category.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { PartCategoryService } from "./part-category.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 29 2021 11:51:09 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: PartCategory
    }
  })
  @Controller('part-category')
  export class PartCategoryController implements CrudController<PartCategory> {
    constructor(public service: PartCategoryService) {}
  }
