
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 29 2021 11:51:09 GMT+0100 (British Summer Time)
 */
@Entity()
export class PartCategory {
  @PrimaryGeneratedColumn() id: number;

  @Column()
  name: string;
  @Column()
  createdBy: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
