
import { Unit } from "src/unit/unit.entity";
import { Job } from 'src/job/job.entity';
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jul 01 2021 12:32:38 GMT+0100 (British Summer Time)
 */
@Entity()
export class TipTicket {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Job) @JoinColumn() job: Job;
  @Column() jobId: number = -1;

  @OneToOne(type => Unit) @JoinColumn() unit: Unit;
  @Column() unitId: number = -1;
  @Column() qty: number = 0;
  @Column() price: number = 0;
  @Column() collectionTicketNumber: string = '';
  @Column() isSignedOff: boolean = false;
  @Column({type: 'text'}) ticketNo: string = '';
  @Column({type: 'boolean'}) deleted: boolean = false;
  @Column() supplierInvoiceNumber: string = '';

  @Column() createdBy: number = -1;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

