
import { DefectStatus } from "./defect-status.entity";
import { Crud, CrudController, Action, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DefectStatusService } from "./defect-status.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 08 2021 15:14:31 GMT+0000 (Coordinated Universal Time)
 */
@Crud({
    model: {
      type: DefectStatus
    }
  })
  @Controller('defect-status')
  @Feature('defect-status')
  export class DefectStatusController implements CrudController<DefectStatus> {
    constructor(public service: DefectStatusService) {}
  }
