

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 08 2021 15:14:31 GMT+0000 (Coordinated Universal Time)
 */
import { Module } from '@nestjs/common';
import { DefectStatus } from './defect-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DefectStatusService } from './defect-status.service';
import { DefectStatusController } from './defect-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([DefectStatus])],
    providers: [DefectStatusService],
    exports: [DefectStatusService],
    controllers: [DefectStatusController],
  })
  export class DefectStatusModule {}
