
import { DefectStatus } from "./defect-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 08 2021 15:14:31 GMT+0000 (Coordinated Universal Time)
 */
@Injectable()
export class DefectStatusService extends TypeOrmCrudService<DefectStatus> {
  constructor(@InjectRepository(DefectStatus) repo) {
    super(repo);
  }
}
