
import { Batch } from "./batch.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Sep 29 2020 12:19:42 GMT+0100 (British Summer Time)
 */
@Injectable()
export class BatchService extends TypeOrmCrudService<Batch> {
  constructor(@InjectRepository(Batch) repo) {
    super(repo);
  }
}
