
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { User } from "src/auth/user.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Sep 29 2020 12:19:42 GMT+0100 (British Summer Time)
 */
@Entity()
export class Batch {
  @PrimaryGeneratedColumn() id: number;

  @Column() filename: string ='';

  @OneToOne(type => User)
  @JoinColumn({ name: "createdBy" })
  user: User;

  @Column() createdBy: number = -1;
  
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
