

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Sep 29 2020 12:19:42 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { Batch } from './batch.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { BatchService } from './batch.service';
import { BatchController } from './batch.controller';
import { InvoiceItemModule } from 'src/invoice-item/invoice-item.module';
import { InvoiceModule } from 'src/invoice/invoice.module';
import { CoreModule } from 'src/core/core.module';

@Module({
    imports: [TypeOrmModule.forFeature([Batch]), InvoiceItemModule, InvoiceModule, CoreModule],
    providers: [BatchService],
    exports: [],
    controllers: [BatchController],
  })
  export class BatchModule {}

