
import { DriverJobStatus } from "./driver-job-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 12:48:33 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class DriverJobStatusService extends TypeOrmCrudService<DriverJobStatus> {
  constructor(@InjectRepository(DriverJobStatus) repo) {
    super(repo);
  }
}
