
import { SavedSearch } from "./saved-search.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { SavedSearchService } from "./saved-search.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Apr 16 2021 13:42:24 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: SavedSearch
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('saved-search')
  export class SavedSearchController implements CrudController<SavedSearch> {
    constructor(public service: SavedSearchService) {}
  }
