

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Apr 16 2021 13:42:24 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { SavedSearch } from './saved-search.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SavedSearchService } from './saved-search.service';
import { SavedSearchController } from './saved-search.controller';

@Module({
    imports: [TypeOrmModule.forFeature([SavedSearch])],
    providers: [SavedSearchService],
    exports: [],
    controllers: [SavedSearchController],
  })
  export class SavedSearchModule {}

