
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Apr 16 2021 13:42:24 GMT+0100 (British Summer Time)
 */
@Entity()
export class SavedSearch {
  @PrimaryGeneratedColumn() id: number;

  @Column() entity: string;
  @Column() data:string;
  @Column() name: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

