
import { SecondaryVehicleType } from "./secondary-vehicletype.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { SecondaryVehicleTypeService } from "./secondary-vehicletype.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Feb 08 2021 10:22:41 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: SecondaryVehicleType
    }
  })
  @Controller('secondary-vehicletype')
  export class SecondaryVehicleTypeController implements CrudController<SecondaryVehicleType> {
    constructor(public service: SecondaryVehicleTypeService) {}
  }
