
import { InvoiceItem } from "./invoice-item.entity";
import { Crud, CrudController, CrudRequest, CrudRequestInterceptor, Feature, ParsedRequest } from "@nestjsx/crud";
import { Body, Controller, Get, Param, Query, UseInterceptors } from "@nestjs/common";
import { InvoiceItemService } from "./invoice-item.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 15:37:53 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: InvoiceItem
    },
    query: {
      join: {
        job: {
          eager: false,
        },

        "job.order": {
          eager: false,
        },
        "job.order.orderLines": {
          eager: false,
        },

        "job.order.orderLines.unit": {
          eager: false,
        },
        "orderLine": {
          eager: false,
        },
        "orderLine.order": {
          eager: false,
        },
        "job.jobAssignment": {
          eager: false,
        },
        "job.jobAssignment.vehicle": {
          eager: false,
        }
      }
    }
  })
  @Controller('invoice-item')
  @Feature('invoice-item')
  export class InvoiceItemController implements CrudController<InvoiceItem> {
    constructor(public service: InvoiceItemService) {}



    @Get('ticket-matches/:ticket')
    async leaderboard(@ParsedRequest() req: CrudRequest, @Param() params, @Body() data: any, @Query() query: any) {
      return await this.service.getTicketMatches(params.ticket);
    }
  }
