

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 15:37:53 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { InvoiceItem } from './invoice-item.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InvoiceItemService } from './invoice-item.service';
import { InvoiceItemController } from './invoice-item.controller';
import { OrderLineModule } from 'src/order-line/order-line.module';
import { CreditLimitModule } from 'src/credit-limit/credit-limit.module';
import { NominalCodeModule } from 'src/nominal-code/nominal-code.module';
import { JobModule } from 'src/job/job.module';

@Module({
    imports: [TypeOrmModule.forFeature([InvoiceItem]), OrderLineModule, CreditLimitModule, NominalCodeModule, JobModule],
    providers: [InvoiceItemService],
    exports: [InvoiceItemService],
    controllers: [InvoiceItemController],
  })
  export class InvoiceItemModule {}

