
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Invoice } from "src/invoice/invoice.entity";
import { Job } from "src/job/job.entity";
import { OrderLine } from "src/order-line/order-line.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 15:37:53 GMT+0100 (British Summer Time)
 */
@Entity()
export class InvoiceItem {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Invoice) @JoinColumn() invoice: Invoice;
  @Column() invoiceId: number;

  @OneToOne(type => Job) @JoinColumn() job: Job;
  @Column() jobId: number;

  @OneToOne(type => OrderLine) @JoinColumn() orderLine: OrderLine;
  @Column() orderLineId: number;

  @Column() yardTradePricingId: number = -1;

  @Column({type: 'date'}) date: string;
  @Column() qty: number;
  @Column() price: number;
  @Column() nominalCode: string;
  @Column({type: 'longtext'}) longDescription: string;
  @Column({type: 'text'}) description: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
