
import { Container } from "./container.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:15:01 GMT+0100 (British Summer Time)
 */
@Injectable()
export class ContainerService extends TypeOrmCrudService<Container> {
  constructor(@InjectRepository(Container) repo) {
    super(repo);
  }

  async setContainerLocation(containerId: number=-1, locationId: number=-1) {
    const container = await this.repo.findOne(containerId);
    container.containerLocationId = locationId;

    await this.repo.save(container);
  }

  async SaveDTO(container) {
    return await this.repo.save(container);
  }
}
