

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:15:01 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { Container } from './container.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerService } from './container.service';
import { ContainerController } from './container.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';
import { CoreModule } from 'src/core/core.module';

@Module({
    imports: [TypeOrmModule.forFeature([Container]), AuthModule, CoreModule],
    providers: [ContainerService],
    exports: [ContainerService],
    controllers: [ContainerController],
  })
  export class ContainerModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('container');
    }
  }

