
import { AssetCategory } from "./asset-category.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 08:24:01 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class AssetCategoryService extends TypeOrmCrudService<AssetCategory> {
  constructor(@InjectRepository(AssetCategory) repo) {
    super(repo);
  }
}
