
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 08:24:01 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class AssetCategory {
  @PrimaryGeneratedColumn() id: number;

  @Column()
  name: string;
  @Column()
  entity: string;
  @Column()
  createdBy: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
