

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 08:24:01 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { AssetCategory } from './asset-category.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AssetCategoryService } from './asset-category.service';
import { AssetCategoryController } from './asset-category.controller';

@Module({
    imports: [TypeOrmModule.forFeature([AssetCategory])],
    providers: [AssetCategoryService],
    exports: [],
    controllers: [AssetCategoryController],
  })
  export class AssetCategoryModule {}

