/**
 * This file is used to generate CURD entities for nest
 *
 * @author Four Ways Technology <Mark J. Lang>

 edit this file then run ts-node generateCurdEntity.ts
 */


const { exec } = require("child_process");
const fs = require("fs");



// Set these variables to the correct values.
const fileName = 'ArticDriverStatus';

const slug = 'artic-driver-status';

exec("nest g module " + slug, (error, stdout, stderr) => {

const entity = `
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On ${new Date()}
 */
@Entity()
export class ${fileName} {
  @PrimaryGeneratedColumn() id: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

`;


fs.writeFileSync(__dirname + `/src/${slug}/${slug}.entity.ts`, entity);


const serviceData = `
import { ${fileName} } from "./${slug}.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On ${new Date()}
 */
@Injectable()
export class ${fileName}Service extends TypeOrmCrudService<${fileName}> {
  constructor(@InjectRepository(${fileName}) repo) {
    super(repo);
  }
}
`;

fs.writeFileSync(__dirname + `/src/${slug}/${slug}.service.ts`, serviceData);


const controllerData = `
import { ${fileName} } from "./${slug}.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ${fileName}Service } from "./${slug}.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On ${new Date()}
 */
@Crud({
    model: {
      type: ${fileName}
    }
  })
  @Controller('${slug}')
  export class ${fileName}Controller implements CrudController<${fileName}> {
    constructor(public service: ${fileName}Service) {}
  }
`;


fs.writeFileSync(__dirname + `/src/${slug}/${slug}.controller.ts`, controllerData);


const moduleData = `

/**
 * This file was generated by Four Ways Technology
 *
 * On ${new Date()}
 */
import { Module } from '@nestjs/common';
import { ${fileName} } from './${slug}.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ${fileName}Service } from './${slug}.service';
import { ${fileName}Controller } from './${slug}.controller';

@Module({
    imports: [TypeOrmModule.forFeature([${fileName}])],
    providers: [${fileName}Service],
    exports: [],
    controllers: [${fileName}Controller],
  })
  export class ${fileName}Module {}

`
fs.unlinkSync(__dirname + `/src/${slug}/${slug}.module.ts`);

fs.writeFileSync(__dirname + `/src/${slug}/${slug}.module.ts`, moduleData);
});
