
import { TransportTimeLineSortOrder } from "./transport-timeline-sort-order.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Nov 19 2021 11:35:30 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class TransportTimeLineSortOrderService extends TypeOrmCrudService<TransportTimeLineSortOrder> {
  constructor(@InjectRepository(TransportTimeLineSortOrder) repo) {
    super(repo);
  }

async deleteAll() {
    await this.repo.createQueryBuilder()
    .delete()
    .from(TransportTimeLineSortOrder)
    .execute();
  }
}
