

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Nov 19 2021 11:35:30 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { TransportTimeLineSortOrder } from './transport-timeline-sort-order.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TransportTimeLineSortOrderService } from './transport-timeline-sort-order.service';
import { TransportTimeLineSortOrderController } from './transport-timeline-sort-order.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TransportTimeLineSortOrder])],
    providers: [TransportTimeLineSortOrderService],
    exports: [],
    controllers: [TransportTimeLineSortOrderController],
  })
  export class TransportTimeLineSortOrderModule {}

