
import { TransportTimeLineSortOrder } from "./transport-timeline-sort-order.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller, Delete, Param } from "@nestjs/common";
import { TransportTimeLineSortOrderService } from "./transport-timeline-sort-order.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Nov 19 2021 11:35:30 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: TransportTimeLineSortOrder
    }
  })
  @Controller('transport-timeline-sort-order')
  export class TransportTimeLineSortOrderController implements CrudController<TransportTimeLineSortOrder> {
    constructor(public service: TransportTimeLineSortOrderService) {}

    @Delete('deleteAll')
    deleteAllByOrderId(@Param() params) {

      this.service.deleteAll();
      return [];
    }
  }
