
import { DriverType } from "./driver-type.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverTypeService } from "./driver-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DriverType
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('driver-type')
  @Feature('driver-type')
  export class DriverTypeController implements CrudController<DriverType> {
    constructor(public service: DriverTypeService) {}
  }
