
import { Sic } from "./sic.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { SicService } from "./sic.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Dec 07 2020 10:55:02 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: Sic
    }
  })
  @Controller('sic')
  @Feature('sic')
  export class SicController implements CrudController<Sic> {
    constructor(public service: SicService) {}
  }
