

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Dec 07 2020 10:55:02 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Sic } from './sic.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SicService } from './sic.service';
import { SicController } from './sic.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Sic])],
    providers: [SicService],
    exports: [],
    controllers: [SicController],
  })
  export class SicModule {}

