
import { VehicleType } from "./vehicle-type.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { VehicleTypeService } from "./vehicle-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 07 2020 15:04:56 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: VehicleType
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('vehicle-type')
  export class VehicleTypeController implements CrudController<VehicleType> {
    constructor(public service: VehicleTypeService) {}
  }
