
import { VehicleType } from "./vehicle-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 07 2020 15:04:56 GMT+0100 (British Summer Time)
 */
@Injectable()
export class VehicleTypeService extends TypeOrmCrudService<VehicleType> {
  constructor(@InjectRepository(VehicleType) repo) {
    super(repo);
  }
}
