
import { SkipRound } from "./skip-round.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 25 2020 14:01:30 GMT+0100 (British Summer Time)
 */
@Injectable()
export class SkipRoundService extends TypeOrmCrudService<SkipRound> {
  constructor(@InjectRepository(SkipRound) repo) {
    super(repo);
  }
}
