

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 10:21:17 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { PriceList } from './price-list.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PriceListService } from './price-list.service';
import { PriceListController } from './price-list.controller';

@Module({
    imports: [TypeOrmModule.forFeature([PriceList])],
    providers: [PriceListService],
    exports: [],
    controllers: [PriceListController],
  })
  export class PriceListModule {}

