
import { PriceList } from "./price-list.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { PriceListService } from "./price-list.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 10:21:17 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: PriceList
    },
    query: {
      join: {
        "account": {
          eager: true,
        }
      }
    }
  })
  @Controller('price-list')
  export class PriceListController implements CrudController<PriceList> {
    constructor(public service: PriceListService) {}
  }
