
import { FuelPrice } from "./fuel-price.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 19 2020 11:33:28 GMT+0100 (British Summer Time)
 */
@Injectable()
export class FuelPriceService extends TypeOrmCrudService<FuelPrice> {
  constructor(@InjectRepository(FuelPrice) repo) {
    super(repo);
  }
}
