
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { FuelType } from "src/fuel-type/fuel-type.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 19 2020 11:33:28 GMT+0100 (British Summer Time)
 */
@Entity()
export class FuelPrice {
  @PrimaryGeneratedColumn() id: number;

  @Column() fuelTypeId: number;
  @OneToOne(type => FuelType) @JoinColumn() fuelType: FuelType;


  @Column({type: 'date'}) effectiveDate: string;
  @Column({type: 'float'}) price: number;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
