
import { DepotDetails } from "./depot-details.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DepotDetailsService } from "./depot-details.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 05 2020 14:08:29 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DepotDetails
    }
  })
  @Controller('depot-details')
  @Feature('depot-details')
  export class DepotDetailsController implements CrudController<DepotDetails> {
    constructor(public service: DepotDetailsService) {}
  }
