

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:49:18 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { OrderLine } from './order-line.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderLineService } from './order-line.service';
import { OrderLineController } from './order-line.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([OrderLine]), AuthModule],
    providers: [OrderLineService],
    exports: [OrderLineService],
    controllers: [OrderLineController],
  })
  export class OrderLineModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('order-line');
    }
  }

