

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:08:49 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { WorkshopNotes } from './workshop-notes.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WorkshopNotesService } from './workshop-notes.service';
import { WorkshopNotesController } from './workshop-notes.controller';

@Module({
    imports: [TypeOrmModule.forFeature([WorkshopNotes])],
    providers: [WorkshopNotesService],
    exports: [],
    controllers: [WorkshopNotesController],
  })
  export class WorkshopNotesModule {}

