
import { InvoiceMethod } from "./invoice-method.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { InvoiceMethodService } from "./invoice-method.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:44:27 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: InvoiceMethod
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('invoice-method')
  export class InvoiceMethodController implements CrudController<InvoiceMethod> {
    constructor(public service: InvoiceMethodService) {}
  }
