
import { InvoiceMethod } from "./invoice-method.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:44:27 GMT+0100 (British Summer Time)
 */
@Injectable()
export class InvoiceMethodService extends TypeOrmCrudService<InvoiceMethod> {
  constructor(@InjectRepository(InvoiceMethod) repo) {
    super(repo);
  }
}
