

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:44:27 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { InvoiceMethod } from './invoice-method.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InvoiceMethodService } from './invoice-method.service';
import { InvoiceMethodController } from './invoice-method.controller';

@Module({
    imports: [TypeOrmModule.forFeature([InvoiceMethod])],
    providers: [InvoiceMethodService],
    exports: [],
    controllers: [InvoiceMethodController],
  })
  export class InvoiceMethodModule {}

