

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Oct 21 2020 10:16:13 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { WeightStatus } from './weight-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WeightStatusService } from './weight-status.service';
import { WeightStatusController } from './weight-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([WeightStatus])],
    providers: [WeightStatusService],
    exports: [],
    controllers: [WeightStatusController],
  })
  export class WeightStatusModule {}

