
import { WeightStatus } from "./weight-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Oct 21 2020 10:16:13 GMT+0100 (British Summer Time)
 */
@Injectable()
export class WeightStatusService extends TypeOrmCrudService<WeightStatus> {
  constructor(@InjectRepository(WeightStatus) repo) {
    super(repo);
  }
}
