
import { WorkshopSubcontractors } from "./workshop-subcontractors.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:09:53 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class WorkshopSubcontractorsService extends TypeOrmCrudService<WorkshopSubcontractors> {
  constructor(@InjectRepository(WorkshopSubcontractors) repo) {
    super(repo);
  }
}
