

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:09:53 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { WorkshopSubcontractors } from './workshop-subcontractors.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { WorkshopSubcontractorsService } from './workshop-subcontractors.service';
import { WorkshopSubcontractorsController } from './workshop-subcontractors.controller';

@Module({
    imports: [TypeOrmModule.forFeature([WorkshopSubcontractors])],
    providers: [WorkshopSubcontractorsService],
    exports: [],
    controllers: [WorkshopSubcontractorsController],
  })
  export class WorkshopSubcontractorsModule {}

