
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:09:53 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class WorkshopSubcontractors {
  @PrimaryGeneratedColumn() id: number;

  @Column({nullable:true,default:'-1'}) parentId: number;
  @Column() ownDepot: boolean;
  @Column() name: string;
  @Column() contact: string;
  @Column() address1: string;
  @Column() address2: string;
  @Column() city: string;
  @Column() postcode: string;
  @Column() phone: string;
  @Column() email: string;
  @Column() notes: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
