

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 07 2020 15:04:21 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { Vehicle } from './vehicle.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VehicleService } from './vehicle.service';
import { VehicleController } from './vehicle.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AssetRegisterController } from 'src/asset-register/asset-register.controller';
import { VehicleDetailsModule } from 'src/vehicledetails/vehicledetails.module';
import { AssetRegisterModule } from 'src/asset-register/asset-register.module';
import { InspectionDates } from 'src/inspection-dates/inspection-dates.entity';
import { InspectionDatesModule } from 'src/inspection-dates/inspection-dates.module';
import { VehicleInspectionAssignmentsModule } from 'src/vehicleinspectionassignments/vehicleinspectionassignments.module';

@Module({
    imports: [TypeOrmModule.forFeature([Vehicle]), AuthModule, AssetRegisterModule, VehicleDetailsModule, InspectionDatesModule, VehicleInspectionAssignmentsModule],
    providers: [VehicleService],
    exports: [VehicleService],
    controllers: [VehicleController],
  })
  export class VehicleModule {
    // configure(consumer: MiddlewareConsumer) {
    //   consumer
    //   .apply(AuthMiddleware)
    //   .forRoutes('vehicle');
    // }
  }

