
import { DriverCheckStatus } from "./driver-check-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 25 2021 13:45:53 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class DriverCheckStatusService extends TypeOrmCrudService<DriverCheckStatus> {
  constructor(@InjectRepository(DriverCheckStatus) repo) {
    super(repo);
  }
}
