
import { DriverCheckStatus } from "./driver-check-status.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverCheckStatusService } from "./driver-check-status.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 25 2021 13:45:53 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: DriverCheckStatus
    }
  })
  @Controller('driver-check-status')
  export class DriverCheckStatusController implements CrudController<DriverCheckStatus> {
    constructor(public service: DriverCheckStatusService) {}
  }
