

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 25 2021 13:45:53 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { DriverCheckStatus } from './driver-check-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverCheckStatusService } from './driver-check-status.service';
import { DriverCheckStatusController } from './driver-check-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([DriverCheckStatus])],
    providers: [DriverCheckStatusService],
    exports: [],
    controllers: [DriverCheckStatusController],
  })
  export class DriverCheckStatusModule {}

