
import { TaxType } from "./tax-type.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { TaxTypeService } from "./tax-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 14:16:54 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: TaxType
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('tax-type')
  export class TaxTypeController implements CrudController<TaxType> {
    constructor(public service: TaxTypeService) {}
  }
