
import { TaxType } from "./tax-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 14:16:54 GMT+0100 (British Summer Time)
 */
@Injectable()
export class TaxTypeService extends TypeOrmCrudService<TaxType> {
  constructor(@InjectRepository(TaxType) repo) {
    super(repo);
  }
}
