

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 14:16:54 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { TaxType } from './tax-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TaxTypeService } from './tax-type.service';
import { TaxTypeController } from './tax-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TaxType])],
    providers: [TaxTypeService],
    exports: [],
    controllers: [TaxTypeController],
  })
  export class TaxTypeModule {}

