
import { DriverHealthReport } from "./driver-health-report.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 19 2021 13:13:30 GMT+0000 (Coordinated Universal Time)
 */
@Injectable()
export class DriverHealthReportService extends TypeOrmCrudService<DriverHealthReport> {
  constructor(@InjectRepository(DriverHealthReport) repo) {
    super(repo);
  }
}
