
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { cpuUsage } from "process";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 19 2021 13:13:30 GMT+0000 (Coordinated Universal Time)
 */
@Entity()
export class DriverHealthReport {
  @PrimaryGeneratedColumn() id: number;

  @Column() driverId: number;
  @Column({type:'date'}) date: string;
  @Column() fitAndHealthy: boolean;
  @Column() drugs: boolean;
  @Column() prescription: boolean;
  @Column() roadAccidents: boolean;
  @Column() personalInjury: boolean;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

