

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 07 2021 09:37:02 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Dashboard } from './dashboard.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DashboardService } from './dashboard.service';
import { DashboardController } from './dashboard.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Dashboard])],
    providers: [DashboardService],
    exports: [],
    controllers: [DashboardController],
  })
  export class DashboardModule {}

