
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 07 2021 09:37:02 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Dashboard {
  @PrimaryGeneratedColumn() id: number;

  @Column()
  userId:number;
  @Column({nullable:true,default:null})
  slotId1:string;
  @Column({nullable:true,default:null})
  slotId2:string;
  @Column({nullable:true,default:null})
  slotId3:string;
  @Column({nullable:true,default:null})
  slotId4:string;
  @Column({nullable:true,default:null})
  slotId5:string;
  @Column({nullable:true,default:null})
  slotId6:string;
  @Column({nullable:true,default:true})
  active:boolean;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
