

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 12:04:27 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { PriceListItem } from './price-list-item.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PriceListItemService } from './price-list-item.service';
import { PriceListItemController } from './price-list-item.controller';

@Module({
    imports: [TypeOrmModule.forFeature([PriceListItem])],
    providers: [PriceListItemService],
    exports: [],
    controllers: [PriceListItemController],
  })
  export class PriceListItemModule {}

