
import { PriceListItem } from "./price-list-item.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { PriceListItemService } from "./price-list-item.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 12:04:27 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: PriceListItem
    },
    query: {
      join: {
        unit: {
          eager: true,
        }
      }
    }
  })
  @Controller('price-list-item')
  export class PriceListItemController implements CrudController<PriceListItem> {
    constructor(public service: PriceListItemService) {}
  }
