
import { CorrespondenceType } from "./correspondence-type.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { CorrespondenceTypeService } from "./correspondence-type.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 18 2021 12:07:26 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: CorrespondenceType
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('correspondence-type')
  export class CorrespondenceTypeController implements CrudController<CorrespondenceType> {
    constructor(public service: CorrespondenceTypeService) {}
  }
