
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 18 2021 12:07:26 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class CorrespondenceType {
  @PrimaryGeneratedColumn() id: number;
  @Column() name: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

