

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Mar 18 2021 12:07:26 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { CorrespondenceType } from './correspondence-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CorrespondenceTypeService } from './correspondence-type.service';
import { CorrespondenceTypeController } from './correspondence-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([CorrespondenceType])],
    providers: [CorrespondenceTypeService],
    exports: [],
    controllers: [CorrespondenceTypeController],
  })
  export class CorrespondenceTypeModule {}

