

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:40:35 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { Order } from './order.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderService } from './order.service';
import { OrderController } from './order.controller';
import { OrderStatusHistoryModule } from 'src/order-status-history/order-status-history.module';
import { CoreModule } from 'src/core/core.module';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { OrderLineModule } from 'src/order-line/order-line.module';
import { OrderLine } from 'src/order-line/order-line.entity';

@Module({
    imports: [OrderStatusHistoryModule, CoreModule, TypeOrmModule.forFeature([Order, OrderLine]), AuthModule, OrderLineModule],
    providers: [OrderService],
    exports: [],
    controllers: [OrderController],
  })
  export class OrderModule {
    // configure(consumer: MiddlewareConsumer) {
    //   consumer
    //   .apply(AuthMiddleware)
    //   .forRoutes('order');
    // }
  }

