
import { QuoteStatusHistory } from "./quote-status-history.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { QuoteStatusHistoryService } from "./quote-status-history.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Feb 25 2021 10:54:03 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: QuoteStatusHistory
    },
    query: {
      join: {
        quoteStatus : {
          eager: true
        },
        user: {
          eager: true,
        }
      }
    }
  })
  @Controller('quote-status-history')
  export class QuoteStatusHistoryController implements CrudController<QuoteStatusHistory> {
    constructor(public service: QuoteStatusHistoryService) {}
  }
