
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { ContractType } from "src/contract-type/contract-type.entity";
import { ContractStatus } from "src/contract-status/contract-status.entity";
import { ContractStatusModule } from "src/contract-status/contract-status.module";
import { Account } from "src/account/account.entity";
import { Recurrence } from "src/recurrence/recurrence.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Dec 31 2020 11:32:01 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Contract {
  @PrimaryGeneratedColumn() id: number;

  @Column()
  contractTypeId: number;

  @OneToOne(type => ContractType) @JoinColumn() contractType: ContractType;

  @Column()
  contractStatusId: number;

  @OneToOne(type => ContractStatus) @JoinColumn() contractStatus: ContractStatus;

  @Column()
  accountId: number;

  @OneToOne(type => Account) @JoinColumn() account: Account;

  @Column({type: 'date'})
  startDate: string;

  @Column({type: 'date'})
  endDate: string;

  @Column()
  contractNumber: number;

  @Column()
  name: string;

  @Column()
  riskLevel: number;

  @Column()
  bagsNo: number;

  @Column()
  cabinetNo: number;

  @Column()
  contractRef: string;

  @Column() recurrenceId: number;
  @OneToOne(type => Recurrence) @JoinColumn() recurrence: Recurrence;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
