

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Dec 31 2020 11:32:01 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Contract } from './contract.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContractService } from './contract.service';
import { ContractController } from './contract.controller';
import { CoreModule } from 'src/core/core.module';

@Module({
    imports: [TypeOrmModule.forFeature([Contract]),CoreModule],
    providers: [ContractService],
    exports: [],
    controllers: [ContractController],
  })
  export class ContractModule {}
