
import { InvoicePeriod } from "./invoice-period.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { InvoicePeriodService } from "./invoice-period.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:43:43 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: InvoicePeriod
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('invoice-period')
  export class InvoicePeriodController implements CrudController<InvoicePeriod> {
    constructor(public service: InvoicePeriodService) {}
  }
