
import { InvoicePeriod } from "./invoice-period.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:43:43 GMT+0100 (British Summer Time)
 */
@Injectable()
export class InvoicePeriodService extends TypeOrmCrudService<InvoicePeriod> {
  constructor(@InjectRepository(InvoicePeriod) repo) {
    super(repo);
  }
}
