
import { CustomerCategory } from "./customer-category.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Oct 02 2020 11:37:44 GMT+0100 (British Summer Time)
 */
@Injectable()
export class CustomerCategoryService extends TypeOrmCrudService<CustomerCategory> {
  constructor(@InjectRepository(CustomerCategory) repo) {
    super(repo);
  }
}
