

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Oct 02 2020 11:37:44 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { CustomerCategory } from './customer-category.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CustomerCategoryService } from './customer-category.service';
import { CustomerCategoryController } from './customer-category.controller';

@Module({
    imports: [TypeOrmModule.forFeature([CustomerCategory])],
    providers: [CustomerCategoryService],
    exports: [],
    controllers: [CustomerCategoryController],
  })
  export class CustomerCategoryModule {}

