
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Oct 02 2020 11:37:44 GMT+0100 (British Summer Time)
 */
@Entity()
export class CustomerCategory {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string = '';
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
