

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 26 2020 14:25:39 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { YardTradePricing } from './yard-trade-pricing.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { YardTradePricingService } from './yard-trade-pricing.service';
import { YardTradePricingController } from './yard-trade-pricing.controller';

@Module({
    imports: [TypeOrmModule.forFeature([YardTradePricing])],
    providers: [YardTradePricingService],
    exports: [YardTradePricingService],
    controllers: [YardTradePricingController],
  })
  export class YardTradePricingModule {}

