
import { YardTradePricing } from "./yard-trade-pricing.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller, Delete, Param } from "@nestjs/common";
import { YardTradePricingService } from "./yard-trade-pricing.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 26 2020 14:25:39 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: YardTradePricing
    },
    query: {
      join: {
        unit: {
          eager: false,
        }
      }
    }
  })
  @Controller('yard-trade-pricing')
  export class YardTradePricingController implements CrudController<YardTradePricing> {
    constructor(public service: YardTradePricingService) {}

    @Delete('deleteAllByYardTradeId/:id')
    deleteAllByYardTrade(@Param() params) {

      if(!params['id']) {
        throw new Error('You must supply an id for deleteAllByYardTradeId');
      }

      this.service.deleteAllForYardTrade(params['id']);
      return [];
    }
  }
