
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { QuoteLine } from "src/quote-line/quote-line.entity";
import { YardTrade } from "src/yard-trade/yard-trade.entity";
import { Unit } from "src/unit/unit.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 26 2020 14:25:39 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class YardTradePricing {
  @PrimaryGeneratedColumn() id: number;

  @Column() yardTradeId: number;
  @OneToOne(type => YardTrade) @JoinColumn() yardTrade: YardTrade;
  
  @Column() quoteLineId: number;
  @OneToOne(type => QuoteLine) @JoinColumn() quoteLine: QuoteLine;

  @Column({type: 'float'}) qty: number;
  @Column({type: 'float'}) price: number;
  @Column() name: string;

  @OneToOne(type => Unit) @JoinColumn() unit: Unit;
  @Column() unitId: number = -1;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
