
import { PartAssignment } from "./part-assignment.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { PartAssignmentService } from "./part-assignment.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Mar 23 2021 16:54:27 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: PartAssignment
    },
    query:{
      join:{
        part: {
          eager:true
        }
      }
    }
  })
  @Controller('part-assignment')
  export class PartAssignmentController implements CrudController<PartAssignment> {
    constructor(public service: PartAssignmentService) {}
  }
