
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 10:24:45 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class SubcontractorType {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string; 

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

