

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 10:24:45 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { SubcontractorType } from './subcontractor-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SubcontractorTypeService } from './subcontractor-type.service';
import { SubcontractorTypeController } from './subcontractor-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([SubcontractorType])],
    providers: [SubcontractorTypeService],
    exports: [],
    controllers: [SubcontractorTypeController],
  })
  export class SubcontractorTypeModule {}

