
import { SubcontractorType } from "./subcontractor-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 10:24:45 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class SubcontractorTypeService extends TypeOrmCrudService<SubcontractorType> {
  constructor(@InjectRepository(SubcontractorType) repo) {
    super(repo);
  }
}
