

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 14:21:52 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { Invoice } from './invoice.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InvoiceService } from './invoice.service';
import { InvoiceController } from './invoice.controller';
import { CustomerDetailsModule } from 'src/customer-details/customer-details.module';
import { CustomerDetailsService } from 'src/customer-details/customer-details.service';
import { InvoiceItemModule } from 'src/invoice-item/invoice-item.module';
import { CoreModule } from 'src/core/core.module';
import { UnitModule } from 'src/unit/unit.module';
import { DriverJobMovementModule } from 'src/driver-job-movement/driver-job-movement.module';
import { DocumentsModule } from 'src/documents/documents.module';
import { DriverJobStatusDetailsModule } from 'src/driver-job-status-details/driver-job-status-details.module';
import { JobModule } from 'src/job/job.module';
import { TipTicketModule } from 'src/tip-ticket/tip-ticket.module';
import { OrderLineModule } from 'src/order-line/order-line.module';
import { InvoiceEmailLogModule } from 'src/invoice-email-log/invoice-email-log.module';

@Module({
    imports: [TypeOrmModule.forFeature([Invoice]), JobModule, CustomerDetailsModule, InvoiceItemModule,UnitModule, DriverJobMovementModule, DriverJobStatusDetailsModule, DocumentsModule, TipTicketModule, CoreModule, OrderLineModule, InvoiceEmailLogModule],
    providers: [InvoiceService],
    exports: [InvoiceService],
    controllers: [InvoiceController],
  })
  export class InvoiceModule {}

