
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { VehicleCheckArea } from "src/vehicle-check-area/vehicle-check-area.entity";
import { VehicleSeverity } from "src/vehicle-severity/vehicle-severity.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Entity()
export class DriverChecks {
  @PrimaryGeneratedColumn() id: number;
  @Column() checkInformation: string;
  @OneToOne(type => VehicleSeverity) @JoinColumn({name:'severity'}) severityDetail: VehicleSeverity;
  @Column() severity: number;
  @Column() isVor: boolean;
  @Column() vehicleTypeId: number;

  @OneToOne(type => VehicleCheckArea) @JoinColumn() vehicleCheckArea: VehicleCheckArea;
  @Column() vehicleCheckAreaId: number;

  @Column() active:boolean;
  @Column() createdBy:number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
