
import { DriverChecks } from "./driver-checks.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverChecksService } from "./driver-checks.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DriverChecks
    },
    query: {
      join: {
        vehicleCheckArea : {
          eager: true
        },
        severityDetail : {
          eager: true
        },
      }
    }
  })
  @Controller('driver-checks')
  export class DriverChecksController implements CrudController<DriverChecks> {
    constructor(public service: DriverChecksService) {}
  }
