
import { Fuel } from "./fuel.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Thu Aug 20 2020 10:23:36 GMT+0100 (British Summer Time)
 */
@Injectable()
export class FuelService extends TypeOrmCrudService<Fuel> {
  constructor(@InjectRepository(Fuel) repo) {
    super(repo);
  }
}
