

/**
 * This file was generated by Four Ways Technology
 * 
 * On Thu Aug 20 2020 10:23:36 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { Fuel } from './fuel.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FuelService } from './fuel.service';
import { FuelController } from './fuel.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Fuel])],
    providers: [FuelService],
    exports: [],
    controllers: [FuelController],
  })
  export class FuelModule {}

