
import { FuelType } from "./fuel-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 19 2020 11:09:29 GMT+0100 (British Summer Time)
 */
@Injectable()
export class FuelTypeService extends TypeOrmCrudService<FuelType> {
  constructor(@InjectRepository(FuelType) repo) {
    super(repo);
  }
}
