
import { FuelType } from "./fuel-type.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { FuelTypeService } from "./fuel-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 19 2020 11:09:29 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: FuelType
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('fuel-type')
  export class FuelTypeController implements CrudController<FuelType> {
    constructor(public service: FuelTypeService) {}
  }
