

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 19 2020 11:09:29 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { FuelType } from './fuel-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FuelTypeService } from './fuel-type.service';
import { FuelTypeController } from './fuel-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([FuelType])],
    providers: [FuelTypeService],
    exports: [],
    controllers: [FuelTypeController],
  })
  export class FuelTypeModule {}

