
import { TimelineTransactionLog } from "./timeline-transaction-log.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Nov 02 2021 16:14:06 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class TimelineTransactionLogService extends TypeOrmCrudService<TimelineTransactionLog> {
  constructor(@InjectRepository(TimelineTransactionLog) repo) {
    super(repo);
  }
}
