

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Nov 02 2021 16:14:06 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { TimelineTransactionLog } from './timeline-transaction-log.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TimelineTransactionLogService } from './timeline-transaction-log.service';
import { TimelineTransactionLogController } from './timeline-transaction-log.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TimelineTransactionLog])],
    providers: [TimelineTransactionLogService],
    exports: [],
    controllers: [TimelineTransactionLogController],
  })
  export class TimelineTransactionLogModule {}

