
import { Invoice } from "src/invoice/invoice.entity";
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Aug 10 2021 14:09:57 GMT+0100 (British Summer Time)
 */
@Entity()
export class CreditNote {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Invoice) @JoinColumn() invoice: Invoice;
  @Column() invoiceId: number = -1;
  @Column() invoiceItemId: number = -1;
  @Column() jobId: number = -1;
  @Column({type: 'text'}) description: string = '';
  @Column({type: 'date'}) date: string = '';
  @Column({type: 'float'}) value: number = 0;

  @Column() emailed: boolean = false;
  @Column({type: 'date'}) emailedDate: string = null;

  @Column() deleted: boolean = false;

  @Column() createdBy: number = -1;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

