
import { CreditNote } from "./credit-note.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Aug 10 2021 14:09:57 GMT+0100 (British Summer Time)
 */
@Injectable()
export class CreditNoteService extends TypeOrmCrudService<CreditNote> {
  constructor(@InjectRepository(CreditNote) repo) {
    super(repo);
  }
}
