

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 15:23:59 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Recurrence } from './recurrence.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { RecurrenceService } from './recurrence.service';
import { RecurrenceController } from './recurrence.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Recurrence])],
    providers: [RecurrenceService],
    exports: [],
    controllers: [RecurrenceController],
  })
  export class RecurrenceModule {}

