
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Incumbents } from "src/incumbents/incumbents.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 28 2021 10:45:15 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class AccountIncumbent {
  @PrimaryGeneratedColumn() id: number;

  @Column({nullable:true,default:-1}) accountId:number;



  @OneToOne(type => Incumbents)
  @JoinColumn({ name: "incumbentId" })
  incumbent: Incumbents;

  @Column({nullable:true,default:-1}) incumbentId:number;

  @Column() notes:string;
  @Column({nullable:true,default:true}) active:boolean;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
