
import { AccountIncumbent } from "./account-incumbent.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { AccountIncumbentService } from "./account-incumbent.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 28 2021 10:45:15 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: AccountIncumbent
    },
    query: {
      cache: 86400000,
      join: {
        incumbent: {
          eager: true
        }
      }
    }
  })
  @Controller('account-incumbent')
  @Feature('account-incumbent')
  export class AccountIncumbentController implements CrudController<AccountIncumbent> {
    constructor(public service: AccountIncumbentService) {}
  }
