

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 28 2021 10:45:15 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { AccountIncumbent } from './account-incumbent.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AccountIncumbentService } from './account-incumbent.service';
import { AccountIncumbentController } from './account-incumbent.controller';

@Module({
    imports: [TypeOrmModule.forFeature([AccountIncumbent])],
    providers: [AccountIncumbentService],
    exports: [],
    controllers: [AccountIncumbentController],
  })
  export class AccountIncumbentModule {}

