
import { ContainerGroup } from "./container-group.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:06 GMT+0100 (British Summer Time)
 */
@Injectable()
export class ContainerGroupService extends TypeOrmCrudService<ContainerGroup> {
  constructor(@InjectRepository(ContainerGroup) repo) {
    super(repo);
  }
}
