
import { ContainerGroup } from "./container-group.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ContainerGroupService } from "./container-group.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:06 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: ContainerGroup
    },
    query: {
      cache: 86400000,
    }
  })
  @Feature('container-group')
  @Controller('container-group')
  export class ContainerGroupController implements CrudController<ContainerGroup> {
    constructor(public service: ContainerGroupService) {}
  }
