

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:06 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { ContainerGroup } from './container-group.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerGroupService } from './container-group.service';
import { ContainerGroupController } from './container-group.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([ContainerGroup]), AuthModule],
    providers: [ContainerGroupService],
    exports: [],
    controllers: [ContainerGroupController],
  })
  export class ContainerGroupModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('container-group');
    }
  }

