
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Mar 19 2021 16:00:07 GMT+0000 (Coordinated Universal Time)
 */
@Entity()
export class CalendarEvent {
  @PrimaryGeneratedColumn() id: number;

  @Column() calendarId: number;
  @Column() name: string;
  @Column({type: 'date'}) date: string;
  @Column({type: 'time'}) startTime: string;
  @Column({type: 'time'}) endTime: string;
  @Column() isFullDay: boolean;
  @Column({type: 'text'}) description: string;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}