
import { CalendarEvent } from "./calendar-event.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Sat Mar 20 2021 18:54:52 GMT+0000 (Coordinated Universal Time)
 */
@Injectable()
export class CalendarEventService extends TypeOrmCrudService<CalendarEvent> {
  constructor(@InjectRepository(CalendarEvent) repo) {
    super(repo);
  }

  async getEventById(id: number) {
    if(!id || id === -1) {
      throw new Error('could not get event by id');
    }

    return await this.repo.find({where:{id: id}});
  }
}
