
import { DefectJob } from "./defect-job.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DefectJobService } from "./defect-job.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Feb 19 2021 12:50:01 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: DefectJob
    },
    query: {
      join: {
        defect: {
          eager: true,
        },
        defectStatus: {
          eager: true,
        },
        "defect.defectAssignment": {
          eager: true,
        },
        "defect.subcontractor":{
          eager:true
        },
        "defect.vehicle": {
          eager: true,
        },
        "defect.vehicleCheckArea": {
          eager: true,
        },
        "defect.inspectionInterval":{
          eager:true
        },
        "defect.vehicleSeverity":{
          eager:true
        },
        "defect.driver" : {
          eager: true
        },
        "defectAssignment": {
          eager: false,
        },
        "defectAssignment.fitter": {
          eager: false,
        }
      }
    }
  })
  @Controller('defect-job')
  export class DefectJobController implements CrudController<DefectJob> {
    constructor(public service: DefectJobService) {}
  }
