
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Defects } from "src/defects/defects.entity";
import { DefectAssignment } from "src/defect-assignment/defect-assignment.entity";
import { DefectStatus } from "src/defect-status/defect-status.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Feb 19 2021 12:50:01 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class DefectJob {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Defects) @JoinColumn() defect: Defects;
  @Column() defectId: number = -1;

  @OneToOne(type => DefectAssignment) @JoinColumn({name:'defectAssignmentId'}) defectAssignment: DefectAssignment;
  @Column() defectAssignmentId: number = -1;

  @Column({type: 'date'}) date: string = '';
  @Column({type: 'datetime', nullable: true}) started: string = '';
  @Column({type: 'datetime', nullable: true}) ended: string = '';
  @Column() blockNumber: number;
  @Column() deleted: boolean = false;
  @Column({type:'text'}) notes:string
  @OneToOne(type => DefectStatus) @JoinColumn({name:'defectStatusId'}) defectStatus: DefectStatus;
  @Column({nullable:true,default:1}) defectStatusId: number;

  @Column({type: 'text'}) fitterSignoff: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
