
import { DefectJob } from "./defect-job.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Feb 19 2021 12:50:01 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class DefectJobService extends TypeOrmCrudService<DefectJob> {
  constructor(@InjectRepository(DefectJob) repo) {
    super(repo);
  }

  async getAllJobsByAssignmentId(assignmentId: number=-1) {
    return await this.repo.find({
      where: {
        defectAssignmentId: assignmentId,
      }
    })
  }

  async saveDTO(dto) {
    return await this.repo.save(dto);
  }
}
