
import { Incumbents } from "./incumbents.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { IncumbentsService } from "./incumbents.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 28 2021 10:48:06 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: Incumbents
    }
  })
  @Controller('incumbents')
  @Feature('incumbents')
  export class IncumbentsController implements CrudController<Incumbents> {
    constructor(public service: IncumbentsService) {}
  }
