
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 28 2021 10:48:06 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Incumbents {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
