

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:50:40 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { FitterAbsenceType } from './fitter-absence-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FitterAbsenceTypeService } from './fitter-absence-type.service';
import { FitterAbsenceTypeController } from './fitter-absence-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([FitterAbsenceType])],
    providers: [FitterAbsenceTypeService],
    exports: [],
    controllers: [FitterAbsenceTypeController],
  })
  export class FitterAbsenceTypeModule {}

