
import { FitterAbsenceType } from "./fitter-absence-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:50:40 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class FitterAbsenceTypeService extends TypeOrmCrudService<FitterAbsenceType> {
  constructor(@InjectRepository(FitterAbsenceType) repo) {
    super(repo);
  }
}
