
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:50:40 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class FitterAbsenceType {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

