

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 26 2020 14:16:46 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { YardTrade } from './yard-trade.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { YardTradeService } from './yard-trade.service';
import { YardTradeController } from './yard-trade.controller';
import { CoreModule } from 'src/core/core.module';
import { YardTradePricingModule } from 'src/yard-trade-pricing/yard-trade-pricing.module';

@Module({
    imports: [TypeOrmModule.forFeature([YardTrade]), CoreModule, YardTradePricingModule],
    providers: [YardTradeService],
    exports: [],
    controllers: [YardTradeController],
  })
  export class YardTradeModule {}

