
import { YardTrade } from "./yard-trade.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";
import { YardTradePricing } from "src/yard-trade-pricing/yard-trade-pricing.entity";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Oct 26 2020 14:16:46 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class YardTradeService extends TypeOrmCrudService<YardTrade> {
  constructor(@InjectRepository(YardTrade) repo) {
    super(repo);
  }



  async getCustomerDetails(accountId: number=-1) {
    // if(!accountId || accountId === -1) {
    //   throw new Error('Must supply a valid account id in getCustomerDetails on yardtrade');
    // }

    return await this.repo.manager.query('Select * from customer_details where accountId = ?', [accountId]);
  }

  async getSicCode(sicId: number=-1) {
    // if(!sicId || sicId === -1) {
    //   throw new Error('Must supply a valid sic id in getSicCode on yardtrade');
    // }

    return await this.repo.manager.query('SELECT * FROM sic where id = ?', [sicId]);
  }
}
