
import { SkipOrderType } from "./skip-order-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 17 2020 15:45:08 GMT+0100 (British Summer Time)
 */
@Injectable()
export class SkipOrderTypeService extends TypeOrmCrudService<SkipOrderType> {
  constructor(@InjectRepository(SkipOrderType) repo) {
    super(repo);
  }
}
