
import { MaterialUpliftCost } from "./material-uplift-cost.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jul 09 2021 15:57:45 GMT+0100 (British Summer Time)
 */
@Injectable()
export class MaterialUpliftCostService extends TypeOrmCrudService<MaterialUpliftCost> {
  constructor(@InjectRepository(MaterialUpliftCost) repo) {
    super(repo);
  }
}
