
import { ContainerLocation } from "./container-location.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ContainerLocationService } from "./container-location.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 18 2020 13:00:54 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: ContainerLocation
    }
  })
  @Controller('container-location')
  export class ContainerLocationController implements CrudController<ContainerLocation> {
    constructor(public service: ContainerLocationService) {}
  }
