
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Account } from "src/account/account.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 18 2020 13:00:54 GMT+0100 (British Summer Time)
 */
@Entity()
export class ContainerLocation {
  @PrimaryGeneratedColumn() id: number;

  @Column({type: 'date'}) date: string;

  @Column() siteId: number;
  @OneToOne(type => Account) @JoinColumn() account: Account;
  
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;  
 
}    
 
