

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 18 2020 13:00:54 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { ContainerLocation } from './container-location.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerLocationService } from './container-location.service';
import { ContainerLocationController } from './container-location.controller';

@Module({
    imports: [TypeOrmModule.forFeature([ContainerLocation])],
    providers: [ContainerLocationService],
    exports: [],
    controllers: [ContainerLocationController],
  })
  export class ContainerLocationModule {}

