
import { CustomerDetails } from "./customer-details.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:45:47 GMT+0100 (British Summer Time)
 */
@Injectable()
export class CustomerDetailsService extends TypeOrmCrudService<CustomerDetails> {
  constructor(@InjectRepository(CustomerDetails) repo) {
    super(repo);
  }
}
