
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Account } from "src/account/account.entity";
import { InvoicePeriod } from "src/invoice-period/invoice-period.entity";
import { InvoiceMethod } from "src/invoice-method/invoice-method.entity";
import { CustomerCategory } from "src/customer-category/customer-category.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 10:45:47 GMT+0100 (British Summer Time)
 */
@Entity()
export class CustomerDetails {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Account) @JoinColumn() account: Account;
  @Column() accountId: number;

  @OneToOne(type => InvoicePeriod) @JoinColumn() invoicePeriod: InvoicePeriod;
  @Column() invoicePeriodId: number;

  @OneToOne(type => InvoiceMethod) @JoinColumn() invoice: InvoiceMethod;
  @Column() invoiceMethodId: number;
  
  @OneToOne(type => CustomerCategory) @JoinColumn() customerCategory: CustomerCategory;
  @Column() customerCategoryId: number;

  @Column() invoiceSplitByPO: boolean = false;
  @Column() invoiceSplitBySite: boolean = false;
  @Column() invoiceSplitByOrderType: boolean = false;

  @Column() licenceNumber: string = '';
  @Column() carrierLicenceNumber: string = '';
  @Column({type: 'date'}) carrierLicenceExpiryDate: string = '';
  @Column() wasteCarrier: string = '';

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
