
import { EnvironmentSettings } from "./environment-settings.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 29 2021 09:38:25 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class EnvironmentSettingsService extends TypeOrmCrudService<EnvironmentSettings> {
  constructor(@InjectRepository(EnvironmentSettings) repo) {
    super(repo);
  }
}
