
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 29 2021 09:38:25 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class EnvironmentSettings {
  @PrimaryGeneratedColumn() id: number;
  @Column({nullable:true,default:-1}) organisationId:number;

  // Company Info
  @Column({nullable:true,default:'Fourways Waste System (Update Company Settings)'}) companyName: string;
  @Column() qrFillColor: string;
  @Column() qrImage: string;
  @Column({nullable:true,default:'Company Number (Update Company Settings)'}) comnpanyNumber: string;

  // System Usage Info
  @Column({nullable:true,default:'kg'}) defaultTareWeightUnit: string;
  @Column() defaultQuoteNoPrefix: string;
  @Column() defaultEmployeeNoPrefix: string;
  @Column({nullable:true,default:-1}) defaultWeighbridgeDepot: number;
  @Column({nullable:true,default:-1}) defaultVehicleDepot: number;

  // Invoicing Settings
  @Column() invoicePrefix: string;
  @Column({nullable:true,default:'x Days (Update Company Settings)'}) invoiceTerms: string;
  @Column({nullable:true,default:'Invoices must be paid etc... (Update Company Settings)'}) invoiceComments: string;
  @Column() address1: string;
  @Column() address2: string;
  @Column() addressCity: string;
  @Column() addressCountry: string;
  @Column() addressPostcode: string;
  @Column() addressEmail: string;
  @Column() addressPhone: string;
  @Column({nullable:true,default:'Left hand T&Cs Block for %REPLACE% (Update Company Settings)'}) wasteTransferTermsBlockA: string;
  @Column({nullable:true,default:'Right hand T&Cs Block for %REPLACE% (Update Company Settings)'}) wasteTransferTermsBlockB: string;


  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
