
import { ContainerSizeType } from "./container-size-type.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ContainerSizeTypeService } from "./container-size-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:45 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: ContainerSizeType
    },
    query: {
      join: {
        vehicleType: {
          eager: true
        },
        unit: {
          eager: true
        },
      }
    }
  })
  @Feature('container-size-type')
  @Controller('container-size-type')
  export class ContainerSizeTypeController implements CrudController<ContainerSizeType> {
    constructor(public service: ContainerSizeTypeService) {}
  }
