

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:45 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { ContainerSizeType } from './container-size-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerSizeTypeService } from './container-size-type.service';
import { ContainerSizeTypeController } from './container-size-type.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([ContainerSizeType]), AuthModule],
    providers: [ContainerSizeTypeService],
    exports: [],
    controllers: [ContainerSizeTypeController],
  })
  export class ContainerSizeTypeModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('container-size-type');
    }
  }

