
import { NominalCode } from "./nominal-code.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { NominalCodeService } from "./nominal-code.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 12 2021 14:14:20 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: NominalCode
    }
  })
  @Controller('nominal-code')
  export class NominalCodeController implements CrudController<NominalCode> {
    constructor(public service: NominalCodeService) {}
  }
