
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 12 2021 14:14:20 GMT+0100 (British Summer Time)
 */
@Entity()
export class NominalCode {
  @PrimaryGeneratedColumn() id: number;

  @Column() code: string;
  @Column() orderTypeId: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

