

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 12 2021 14:14:20 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { NominalCode } from './nominal-code.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { NominalCodeService } from './nominal-code.service';
import { NominalCodeController } from './nominal-code.controller';

@Module({
    imports: [TypeOrmModule.forFeature([NominalCode])],
    providers: [NominalCodeService],
    exports: [NominalCodeService],
    controllers: [NominalCodeController],
  })
  export class NominalCodeModule {}

