
import { NominalCode } from "./nominal-code.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 12 2021 14:14:20 GMT+0100 (British Summer Time)
 */
@Injectable()
export class NominalCodeService extends TypeOrmCrudService<NominalCode> {
  constructor(@InjectRepository(NominalCode) repo) {
    super(repo);
  }

  async getAll() {
    return await this.repo.find();
  }
}
