
import { PublicFormToken } from "./public-form-token.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 07 2021 16:04:54 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class PublicFormTokenService extends TypeOrmCrudService<PublicFormToken> {
  constructor(@InjectRepository(PublicFormToken) repo) {
    super(repo);
  }
}
