
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 07 2021 16:04:54 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class PublicFormToken {
  @PrimaryGeneratedColumn() id: number;
  @Column() token: string;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

