
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jun 04 2021 13:13:22 GMT+0100 (British Summer Time)
 */
@Entity()
export class UserSkill {
  @PrimaryGeneratedColumn() id: number;

  @Column() userId: number = -1;  
  @Column() orderTypeId: number = -1;
  @Column() isPrimary: boolean = false;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

