

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 08 2021 15:14:31 GMT+0000 (Coordinated Universal Time)
 */
import { Module } from '@nestjs/common';
import { CreditLimit } from './credit-limit.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CreditLimitService } from './credit-limit.service';
import { CreditLimitController } from './credit-limit.controller';

@Module({
    imports: [TypeOrmModule.forFeature([CreditLimit])],
    providers: [CreditLimitService],
    exports: [CreditLimitService],
    controllers: [CreditLimitController],
  })
  export class CreditLimitModule {}

