
import { OrderStatus } from "./order-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:39:35 GMT+0100 (British Summer Time)
 */
@Injectable()
export class OrderStatusService extends TypeOrmCrudService<OrderStatus> {
  constructor(@InjectRepository(OrderStatus) repo) {
    super(repo);
  }
}
