
import { OrderStatus } from "./order-status.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { OrderStatusService } from "./order-status.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:39:35 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: OrderStatus
    },
    query: {
      cache: 86400000,
    }
  })
  @Controller('order-status')
  export class OrderStatusController implements CrudController<OrderStatus> {
    constructor(public service: OrderStatusService) {}
  }
