

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 12:50:28 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { DriverJobMovement } from './driver-job-movement.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverJobMovementService } from './driver-job-movement.service';
import { DriverJobMovementController } from './driver-job-movement.controller';
import { CoreModule } from 'src/core/core.module';
import { UnitModule } from 'src/unit/unit.module';
import { DriverJobStatusDetailsModule } from 'src/driver-job-status-details/driver-job-status-details.module';
import { DocumentsModule } from 'src/documents/documents.module';

@Module({
    imports: [TypeOrmModule.forFeature([DriverJobMovement]), CoreModule, UnitModule, DriverJobStatusDetailsModule, DocumentsModule],
    providers: [DriverJobMovementService],
    exports: [DriverJobMovementService],
    controllers: [DriverJobMovementController],
  })
  export class DriverJobMovementModule {}

