
import { VehicleVOR } from "./vehicle-vor.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { VehicleVORService } from "./vehicle-vor.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 13:36:38 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: VehicleVOR
    },
    query: {
      join: {
        vehicle : {
          eager: true
        },
      }
    }
  })
  @Feature('vehicle-vor')
  @Controller('vehicle-vor')
  export class VehicleVORController implements CrudController<VehicleVOR> {
    constructor(public service: VehicleVORService) {}
  }
