
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Vehicle } from "src/vehicle/vehicle.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Aug 10 2020 13:36:38 GMT+0100 (British Summer Time)
 */
@Entity()
export class VehicleVOR {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Vehicle) @JoinColumn() vehicle: Vehicle;
  @Column() vehicleId: number;

  @Column({type: 'date'}) startDate: string;
  @Column({type: 'date', nullable:true, default:null}) endDate: string;
  @Column({type: 'text'}) notes: string;
  @Column({nullable:true,default:0}) deleted: boolean;


  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
