
import { InspectionDates } from "./inspection-dates.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { InspectionDatesService } from "./inspection-dates.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Aug 25 2020 13:41:01 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: InspectionDates
    },
    query:{
      join:{
        inspectionInterval:{
          eager:true
        },
        defect:{
          eager:true
        },
        vehicle:{
          eager:true
        }
      }
    }
  })
  @Controller('inspection-dates')
  export class InspectionDatesController implements CrudController<InspectionDates> {
    constructor(public service: InspectionDatesService) {}
  }
