
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { VehicleInspectionIntervals } from "src/vehicleinspectionintervals/vehicleinspectionintervals.entity";
import { Defects } from "src/defects/defects.entity";
import { Vehicle } from "src/vehicle/vehicle.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Aug 25 2020 13:41:01 GMT+0100 (British Summer Time)
 */
@Entity()
export class InspectionDates {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Vehicle) @JoinColumn() vehicle: Vehicle;
  @Column({nullable:true,default:-1}) vehicleId: number;
  @OneToOne(type => VehicleInspectionIntervals) @JoinColumn({name: 'inspectionIntervalId'}) inspectionInterval: VehicleInspectionIntervals;
  @Column({nullable:true,default:-1}) inspectionIntervalId: string;
  @OneToOne(type => Defects) @JoinColumn({name: 'defectId'}) defect: Defects;
  @Column({nullable:true,default:-1}) defectId: string;
  @Column({nullable:true,default:null}) date: string;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
