
import { Calendar } from "./calendar.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { CalendarService } from "./calendar.service";
import { CalendarEvent } from "src/calendar-event/calendar-event.entity";
import moment = require("moment");
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Mar 19 2021 15:48:24 GMT+0000 (Coordinated Universal Time)
 */
@Crud({
    model: {
      type: Calendar
    }
  })
  @Controller('calendar')
  export class CalendarController implements CrudController<Calendar> {
    constructor(public service: CalendarService) {}
  }
