
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Mar 19 2021 15:48:24 GMT+0000 (Coordinated Universal Time)
 */
@Entity()
export class Calendar {
  @PrimaryGeneratedColumn() id: number;
  
  @Column() name: string;
  @Column() colour: string;
  @Column({type: 'text'}) description: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

