
import { Grade } from "src/grade/grade.entity";
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 05 2021 10:14:21 GMT+0100 (British Summer Time)
 */
@Entity()
export class JobSmartWaste {
  @PrimaryGeneratedColumn() id: number;

  @Column() jobId: number;

  @OneToOne(type => Grade) @JoinColumn({name: 'ewcCodeId'}) ewcCode: Grade;
  @Column() ewcCodeId: number;


  @Column({type: 'text'}) notes: string;
  @Column() percentage: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

