
import { JobSmartWaste } from "./job-smart-waste.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { JobSmartWasteService } from "./job-smart-waste.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 05 2021 10:14:21 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: JobSmartWaste
    },
    query: {
      join: {
        ewcCode: {
          eager: false,
        }
      }
    }
  })
  @Controller('job-smart-waste')
  export class JobSmartWasteController implements CrudController<JobSmartWaste> {
    constructor(public service: JobSmartWasteService) {}
  }
