

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed May 05 2021 10:14:21 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { JobSmartWaste } from './job-smart-waste.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { JobSmartWasteService } from './job-smart-waste.service';
import { JobSmartWasteController } from './job-smart-waste.controller';

@Module({
    imports: [TypeOrmModule.forFeature([JobSmartWaste])],
    providers: [JobSmartWasteService],
    exports: [],
    controllers: [JobSmartWasteController],
  })
  export class JobSmartWasteModule {}

