
import { FitterAbsenceType } from "src/fitter-absence-type/fitter-absence-type.entity";
import { Fitter } from "src/fitter/fitter.entity";
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:56:45 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class FitterAbsence {
  @PrimaryGeneratedColumn() id: number;

  @Column() fitterId: number;
  @OneToOne(type => Fitter) @JoinColumn() fitter: Fitter;
  
  @Column() fitterAbsenceTypeId: number;
  @OneToOne(type => FitterAbsenceType) @JoinColumn() fitterAbsenceType: FitterAbsenceType;

  
  @Column({type: 'date'}) startDate: string;
  @Column({type: 'date'}) endDate: string;
  @Column({type: 'text'}) notes: string;

  @Column() createdBy: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

