
import { FitterAbsence } from "./fitter-absence.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { FitterAbsenceService } from "./fitter-absence.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:56:45 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: FitterAbsence
    },
    query: {
      join: {
        fitter : {
          eager: true
        },
        fitterAbsenceType: {
          eager: true,
        }
      }
    }
  })
  @Controller('fitter-absence')
  export class FitterAbsenceController implements CrudController<FitterAbsence> {
    constructor(public service: FitterAbsenceService) {}
  }
