
import { FitterAbsence } from "./fitter-absence.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:56:45 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class FitterAbsenceService extends TypeOrmCrudService<FitterAbsence> {
  constructor(@InjectRepository(FitterAbsence) repo) {
    super(repo);
  }
}
