

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 14:56:45 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { FitterAbsence } from './fitter-absence.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FitterAbsenceService } from './fitter-absence.service';
import { FitterAbsenceController } from './fitter-absence.controller';

@Module({
    imports: [TypeOrmModule.forFeature([FitterAbsence])],
    providers: [FitterAbsenceService],
    exports: [],
    controllers: [FitterAbsenceController],
  })
  export class FitterAbsenceModule {}

