
import { Defects } from "./defects.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DefectsService } from "./defects.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 09:22:35 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: Defects
    },
    query:{
      join:{
        subcontractor:{
          eager:true
        },
        vehicle: {
          eager: true,
        },
        vehicleCheckArea: {
          eager: true,
        },
        inspectionInterval:{
          eager:true
        },
        vehicleSeverity:{
          eager:true
        },
        driver : {
          eager: true
        },
        depot : {
          eager: true
        },
        defectStatus : {
          eager: true
        },

        // Non eager stuff for timeline
        "vehicle.vehicleType": {
          eager: false,
        }
      }
    }
  })
  @Controller('defects')
  export class DefectsController implements CrudController<Defects> {
    constructor(public service: DefectsService) {}
  }
