
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { WorkshopSubcontractors } from "src/workshop-subcontractors/workshop-subcontractors.entity";
import { VehicleInspectionIntervals } from "src/vehicleinspectionintervals/vehicleinspectionintervals.entity";
import { VehicleSeverity } from "src/vehicle-severity/vehicle-severity.entity";
import { Driver } from "src/driver/driver.entity";
import { Vehicle } from "src/vehicle/vehicle.entity";
import { VehicleCheckArea } from "src/vehicle-check-area/vehicle-check-area.entity";
import { Subcontractor } from "src/subcontractor/subcontractor.entity";
import { Account } from "src/account/account.entity";
import { DefectStatus } from "src/defect-status/defect-status.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 09:22:35 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Defects {
  @PrimaryGeneratedColumn() id: number;

  @OneToOne(type => Vehicle) @JoinColumn() vehicle: Vehicle;
  @Column() vehicleId: number;

  @Column({nullable: true, default: -1}) driverId: number;
  @OneToOne(type => Driver) @JoinColumn() driver: Driver;
  @Column({nullable:true,default: 0}) driverReportStatus: number;

  @OneToOne(type => VehicleCheckArea) @JoinColumn() vehicleCheckArea: VehicleCheckArea;
  @Column() vehicleCheckAreaId: number;

  @Column({type:'text'}) poNumber: string;

  @Column({type: 'text'}) description: string;
  @Column({nullable:true,default: null,type:'date'}) bookedFor: string;

  @OneToOne(type => VehicleSeverity) @JoinColumn({name:'vehicleSeverityId'}) vehicleSeverity: VehicleSeverity;
  @Column() vehicleSeverityId: number;

  @OneToOne(type => VehicleInspectionIntervals) @JoinColumn({name: 'vehicleInspectionIntervalsId'}) inspectionInterval: VehicleInspectionIntervals;
  @Column({nullable: true, default: -1}) vehicleInspectionIntervalsId: number;

  @Column({nullable: true, default: -1}) defectAssignmentId: number = -1;

  @Column({nullable:true, default:null}) started: string;
  @Column({nullable:true, default:null}) ended: string;

  @OneToOne(type => Subcontractor) @JoinColumn({name:'workshopSubcontractorsId'}) subcontractor: Subcontractor;
  @Column({nullable: true, default: -1}) workshopSubcontractorsId: number;

  @OneToOne(type => Account) @JoinColumn({name:'depotId'}) depot: Account;
  @Column() depotId: number;
  @Column({nullable:true,default: null}) finalSignoff: string;
  @Column({type:'datetime',nullable:true,default:null}) signoffDate: string;

  @OneToOne(type => DefectStatus) @JoinColumn({name:'defectStatusId'}) defectStatus: DefectStatus;
  @Column({nullable:true,default:1}) defectStatusId: number;

  @Column({type: 'text'}) signoffNotes: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
