

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 09:22:35 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Defects } from './defects.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DefectsService } from './defects.service';
import { DefectsController } from './defects.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Defects])],
    providers: [DefectsService],
    exports: [],
    controllers: [DefectsController],
  })
  export class DefectsModule {}

