

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 07 2020 21:27:29 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { Driver } from './driver.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverService } from './driver.service';
import { DriverController } from './driver.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([Driver]), AuthModule],
    providers: [DriverService],
    exports: [DriverService],
    controllers: [DriverController],
  })
  export class DriverModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('driver');
    }
  }

