

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 25 2020 13:41:01 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { JobStatus } from './job-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { JobStatusService } from './job-status.service';
import { JobStatusController } from './job-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([JobStatus])],
    providers: [JobStatusService],
    exports: [],
    controllers: [JobStatusController],
  })
  export class JobStatusModule {}

