

/**
 * This file was generated by Four Ways Technology
 * 
 * On Sun Aug 09 2020 14:30:49 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { DriverAbsence } from './driver-absence.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverAbsenceService } from './driver-absence.service';
import { DriverAbsenceController } from './driver-absence.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([DriverAbsence]), AuthModule],
    providers: [DriverAbsenceService],
    exports: [],
    controllers: [DriverAbsenceController],
  })
  export class DriverAbsenceModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('driver-absence');
    }
  }

