
import { DriverAbsence } from "./driver-absence.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverAbsenceService } from "./driver-absence.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Sun Aug 09 2020 14:30:49 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DriverAbsence
    },
    query: {
      join: {
        driver : {
          eager: true
        },
        driverAbsenceType: {
          eager: true,
        }
      }
    }
  })
  @Feature('driver-absence')
  @Controller('driver-absence')
  export class DriverAbsenceController implements CrudController<DriverAbsence> {
    constructor(public service: DriverAbsenceService) {}
  }
