
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { DriverAbsenceType } from "src/driver-absence-type/driver-absence-type.entity";
import { Driver } from "src/driver/driver.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Sun Aug 09 2020 14:30:49 GMT+0100 (British Summer Time)
 */
@Entity()
export class DriverAbsence {
  @PrimaryGeneratedColumn() id: number;

  @Column() driverId: number;
  @OneToOne(type => Driver) @JoinColumn() driver: Driver;
  
  @Column() driverAbsenceTypeId: number;
  @OneToOne(type => DriverAbsenceType) @JoinColumn() driverAbsenceType: DriverAbsenceType;

  
  @Column({type: 'date'}) startDate: string;
  @Column({type: 'date'}) endDate: string;
  @Column({type: 'text'}) notes: string;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
