
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 18 2020 14:29:12 GMT+0100 (British Summer Time)
 */
@Entity()
export class DriverBonusLevel {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;
  @Column() value: number;

  @Column() createdBy: number = -1;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
