
import { Fitter } from "./fitter.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 14:16:12 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class FitterService extends TypeOrmCrudService<Fitter> {
  constructor(@InjectRepository(Fitter) repo) {
    super(repo);
  }
}
