

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 14:16:12 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Fitter } from './fitter.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { FitterService } from './fitter.service';
import { FitterController } from './fitter.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Fitter])],
    providers: [FitterService],
    exports: [],
    controllers: [FitterController],
  })
  export class FitterModule {}

