
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Account } from "src/account/account.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Feb 17 2021 14:16:12 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Fitter {
  @PrimaryGeneratedColumn() id: number;

  @Column({nullable:true,default:-1}) depotId: number;
  @OneToOne(type => Account) @JoinColumn() depot: Account;

  @Column() firstName: string;
  @Column() middleName: string;
  @Column() lastName: string;
  @Column() contact: string;
  @Column() employeeNumber: string;
  @Column() active: boolean;
  @Column({type:'text',nullable:true,default:null}) notes: string;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
