
import { InvoiceStatus } from "./invoice-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 23 2020 14:13:36 GMT+0100 (British Summer Time)
 */
@Injectable()
export class InvoiceStatusService extends TypeOrmCrudService<InvoiceStatus> {
  constructor(@InjectRepository(InvoiceStatus) repo) {
    super(repo);
  }
}
