

/**
 * This file was generated by Four Ways Technology
 * 
 * On Sun Aug 09 2020 14:33:06 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { DriverAbsenceType } from './driver-absence-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverAbsenceTypeService } from './driver-absence-type.service';
import { DriverAbsenceTypeController } from './driver-absence-type.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([DriverAbsenceType]), AuthModule],
    providers: [DriverAbsenceTypeService],
    exports: [],
    controllers: [DriverAbsenceTypeController],
  })
  export class DriverAbsenceTypeModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('driver-absence-type');
    }
  }

