
import { DriverAbsenceType } from "./driver-absence-type.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverAbsenceTypeService } from "./driver-absence-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Sun Aug 09 2020 14:33:06 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DriverAbsenceType
    },
    query: {
      cache: 86400000,
    }
  })
  @Feature('driver-absence-type')
  @Controller('driver-absence-type')
  export class DriverAbsenceTypeController implements CrudController<DriverAbsenceType> {
    constructor(public service: DriverAbsenceTypeService) {}
  }
