

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 08:23:28 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { AssetRegister } from './asset-register.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AssetRegisterService } from './asset-register.service';
import { AssetRegisterController } from './asset-register.controller';

@Module({
    imports: [TypeOrmModule.forFeature([AssetRegister])],
    providers: [AssetRegisterService],
    exports: [AssetRegisterService],
    controllers: [AssetRegisterController],
  })
  export class AssetRegisterModule {}

