
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { VehicleDetails } from './vehicledetails.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VehicleDetailsService } from './vehicledetails.service';
import { VehicleDetailsController } from './vehicledetails.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([VehicleDetails]), AuthModule],
    providers: [VehicleDetailsService],
    exports: [VehicleDetailsService],
    controllers: [VehicleDetailsController],
  })
  export class VehicleDetailsModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('vehicledetails');
    }
  }
