

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Aug 16 2021 10:58:13 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { PriceListOtherItem } from './price-list-other-item.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PriceListOtherItemService } from './price-list-other-item.service';
import { PriceListOtherItemController } from './price-list-other-item.controller';

@Module({
    imports: [TypeOrmModule.forFeature([PriceListOtherItem])],
    providers: [PriceListOtherItemService],
    exports: [],
    controllers: [PriceListOtherItemController],
  })
  export class PriceListOtherItemModule {}

