
import { PriceListOtherItem } from "./price-list-other-item.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { PriceListOtherItemService } from "./price-list-other-item.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Aug 16 2021 10:58:13 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: PriceListOtherItem
    }
  })
  @Controller('price-list-other-item')
  export class PriceListOtherItemController implements CrudController<PriceListOtherItem> {
    constructor(public service: PriceListOtherItemService) {}
  }
