
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { VehicleType } from "src/vehicle-type/vehicle-type.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Entity()
export class VehicleCheckArea {
  @PrimaryGeneratedColumn() id: number;
  @Column() name: string;
  @Column({nullable:true, default:0}) vehicleTypeId: number;
  @OneToOne(type => VehicleType) @JoinColumn() vehicleType: VehicleType;
  @Column() icon: string;

  @Column() createdBy:number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
