
import { VehicleCheckArea } from "./vehicle-check-area.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { VehicleCheckAreaService } from "./vehicle-check-area.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: VehicleCheckArea
    },
    query:{
      join:{
        vehicleType : {
          eager: true
        },
      }
    }
  })
  @Controller('vehicle-check-area')
  export class VehicleCheckAreaController implements CrudController<VehicleCheckArea> {
    constructor(public service: VehicleCheckAreaService) {}
  }
