
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 29 2021 09:37:41 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class UserSettings {
  @PrimaryGeneratedColumn() id: number;

  @Column({nullable:true,default:-1}) userId:number;

  // Transport timelines
  @Column({nullable:true,default:true}) timelineOrientationTipper: boolean;
  @Column({nullable:true,default:true}) timelineOrientationGrab: boolean;
  @Column({nullable:true,default:true}) timelineOrientationConcrete: boolean;
  @Column({nullable:true,default:true}) timelineOrientationSweeper: boolean;
  @Column({nullable:true,default:true}) timelineOrientationShredder: boolean;
  @Column({nullable:true,default:true}) timelineOrientationTanker: boolean;

  // Other Timelines
  @Column({nullable:true,default:true}) timelineOrientationSkip: boolean;
  @Column({nullable:true,default:true}) timelineOrientationArtic: boolean;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
