
import { UserSettings } from "./user-settings.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { UserSettingsService } from "./user-settings.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 29 2021 09:37:41 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: UserSettings
    }
  })
  @Controller('user-settings')
  export class UserSettingsController implements CrudController<UserSettings> {
    constructor(public service: UserSettingsService) {}
  }
