
import { ShredderOrderType } from "./shredder-order-type.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ShredderOrderTypeService } from "./shredder-order-type.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 14 2021 11:37:49 GMT+0000 (Coordinated Universal Time)
 */
@Crud({
    model: {
      type: ShredderOrderType
    }
  })
  @Feature('shredder-order-type')
  @Controller('shredder-order-type')
  export class ShredderOrderTypeController implements CrudController<ShredderOrderType> {
    constructor(public service: ShredderOrderTypeService) {}
  }
