
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Jan 14 2021 11:37:49 GMT+0000 (Coordinated Universal Time)
 */
@Entity()
export class ShredderOrderType {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

