
import { OrderType } from "./order-type.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { OrderTypeService } from "./order-type.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 12 2020 10:14:39 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: OrderType
    },
    query: {
      cache: 86400000,
    }
  })
  @Feature('order-type')
  @Controller('order-type')
  export class OrderTypeController implements CrudController<OrderType> {
    constructor(public service: OrderTypeService) {}
  }
