

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 12 2020 10:14:39 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { OrderType } from './order-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderTypeService } from './order-type.service';
import { OrderTypeController } from './order-type.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([OrderType]), AuthModule],
    providers: [OrderTypeService],
    exports: [],
    controllers: [OrderTypeController],
  })
  export class OrderTypeModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('order-type');
    }
  }

