
import { OrderType } from "./order-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Aug 12 2020 10:14:39 GMT+0100 (British Summer Time)
 */
@Injectable()
export class OrderTypeService extends TypeOrmCrudService<OrderType> {
  constructor(@InjectRepository(OrderType) repo) {
    super(repo);
  }
}
