
import { Messaging } from "./messaging.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Mar 16 2021 13:50:02 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class MessagingService extends TypeOrmCrudService<Messaging> {
  constructor(@InjectRepository(Messaging) repo) {
    super(repo);
  }
}
