

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Mar 16 2021 13:50:02 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Messaging } from './messaging.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { MessagingService } from './messaging.service';
import { MessagingController } from './messaging.controller';
import { CoreModule } from 'src/core/core.module';
import { JobModule } from 'src/job/job.module';

@Module({
    imports: [TypeOrmModule.forFeature([Messaging]), JobModule, CoreModule],
    providers: [MessagingService],
    exports: [],
    controllers: [MessagingController],
  })
  export class MessagingModule {}

