
import { JobSignoffStatus } from "./job-signoff-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Sep 11 2020 14:39:05 GMT+0100 (British Summer Time)
 */
@Injectable()
export class JobSignoffStatusService extends TypeOrmCrudService<JobSignoffStatus> {
  constructor(@InjectRepository(JobSignoffStatus) repo) {
    super(repo);
  }
}
