

/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Sep 11 2020 14:39:05 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { JobSignoffStatus } from './job-signoff-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { JobSignoffStatusService } from './job-signoff-status.service';
import { JobSignoffStatusController } from './job-signoff-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([JobSignoffStatus])],
    providers: [JobSignoffStatusService],
    exports: [],
    controllers: [JobSignoffStatusController],
  })
  export class JobSignoffStatusModule {}

