
import { YardTradeSmartWaste } from "./yard-trade-smart-waste.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri May 21 2021 15:19:44 GMT+0100 (British Summer Time)
 */
@Injectable()
export class YardTradeSmartWasteService extends TypeOrmCrudService<YardTradeSmartWaste> {
  constructor(@InjectRepository(YardTradeSmartWaste) repo) {
    super(repo);
  }
}
