
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri May 21 2021 15:19:44 GMT+0100 (British Summer Time)
 */
@Entity()
export class YardTradeSmartWaste {
  @PrimaryGeneratedColumn() id: number;

  @Column() yardTradeId: number;
  @Column() ewcCodeId: number;
  @Column({type: 'text'}) notes: string;
  @Column() percentage: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;


}

