
import { YardTradeSmartWaste } from "./yard-trade-smart-waste.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { YardTradeSmartWasteService } from "./yard-trade-smart-waste.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri May 21 2021 15:19:44 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: YardTradeSmartWaste
    }
  })
  @Controller('yard-trade-smart-waste')
  export class YardTradeSmartWasteController implements CrudController<YardTradeSmartWaste> {
    constructor(public service: YardTradeSmartWasteService) {}
  }
