

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri May 21 2021 15:19:44 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { YardTradeSmartWaste } from './yard-trade-smart-waste.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { YardTradeSmartWasteService } from './yard-trade-smart-waste.service';
import { YardTradeSmartWasteController } from './yard-trade-smart-waste.controller';

@Module({
    imports: [TypeOrmModule.forFeature([YardTradeSmartWaste])],
    providers: [YardTradeSmartWasteService],
    exports: [],
    controllers: [YardTradeSmartWasteController],
  })
  export class YardTradeSmartWasteModule {}

