

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 09 2020 14:50:40 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { Grade } from './grade.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { GradeService } from './grade.service';
import { GradeController } from './grade.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Grade])],
    providers: [GradeService],
    exports: [],
    controllers: [GradeController],
  })
  export class GradeModule {}

