
import { Grade } from "./grade.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 09 2020 14:50:40 GMT+0100 (British Summer Time)
 */
@Injectable()
export class GradeService extends TypeOrmCrudService<Grade> {
  constructor(@InjectRepository(Grade) repo) {
    super(repo);
  }
}
