
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Wed Sep 09 2020 14:50:40 GMT+0100 (British Summer Time)
 */
@Entity()
export class Grade {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;
  @Column({type: 'longtext'}) ewcCodes: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
