

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 26 2021 10:25:21 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { DriverCheckGroup } from './driver-check-group.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverCheckGroupService } from './driver-check-group.service';
import { DriverCheckGroupController } from './driver-check-group.controller';

@Module({
    imports: [TypeOrmModule.forFeature([DriverCheckGroup])],
    providers: [DriverCheckGroupService],
    exports: [],
    controllers: [DriverCheckGroupController],
  })
  export class DriverCheckGroupModule {}

