
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Vehicle } from "src/vehicle/vehicle.entity";
import { Driver } from "src/driver/driver.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 26 2021 10:25:21 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class DriverCheckGroup {
  @PrimaryGeneratedColumn() id: number;

  @Column() date: string;
  @OneToOne(type => Vehicle) @JoinColumn() vehicle: Vehicle;
  @Column({nullable:true,default:-1}) vehicleId: number;
  @OneToOne(type => Driver) @JoinColumn() driver: Driver;
  @Column({nullable:true,default:-1}) driverId: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
