

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Sep 21 2020 16:20:22 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { TippingPrices } from './tipping-prices.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TippingPricesService } from './tipping-prices.service';
import { TippingPricesController } from './tipping-prices.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TippingPrices])],
    providers: [TippingPricesService],
    exports: [],
    controllers: [TippingPricesController],
  })
  export class TippingPricesModule {}

