

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { VehicleSeverity } from './vehicle-severity.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VehicleSeverityService } from './vehicle-severity.service';
import { VehicleSeverityController } from './vehicle-severity.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([VehicleSeverity]), AuthModule],
    providers: [VehicleSeverityService],
    exports: [],
    controllers: [VehicleSeverityController],
  })
  export class VehicleSeverityModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('vehicle-severity');
    }
  }
