
import { VehicleSeverity } from "./vehicle-severity.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { VehicleSeverityService } from "./vehicle-severity.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: VehicleSeverity
    }
  })
  @Controller('vehicle-severity')
  export class VehicleSeverityController implements CrudController<VehicleSeverity> {
    constructor(public service: VehicleSeverityService) {}
  }
