
import { Order } from "src/order/order.entity";
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Sep 07 2023 10:10:45 GMT+0100 (British Summer Time)
 */
@Entity()
export class OrderProvision {
  @PrimaryGeneratedColumn() id: number;
  
  @OneToOne(type => Order) @JoinColumn() order: Order;
  @Column() orderId: number = -1;

  @Column() unitId: number = -1;
  @Column({type: 'float'}) amount: number = 0;
  @Column({type: 'date'}) date: string;
  @Column({type: 'text'}) notes: string = '';
  @Column({type: 'float'}) allocated: number = 0;
  @Column() createdBy: number = -1;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

