
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:10:32 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Documents {
  @PrimaryGeneratedColumn() id: number;

  @Column() type: string;
  @Column() entity: string;
  @Column({nullable:true,default:-1}) entityId: number;
  @Column() filename: string;
  @Column() filetype: string;
  @Column() originalFilename: string;


  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}
