
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 19 2021 10:41:46 GMT+0000 (Coordinated Universal Time)
 */
@Entity()
export class ReportTipIssue {
  @PrimaryGeneratedColumn() id: number;

  @Column() name: string;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

