
import { ReportTipIssue } from "./report-tip-issue.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ReportTipIssueService } from "./report-tip-issue.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Jan 19 2021 10:41:46 GMT+0000 (Coordinated Universal Time)
 */
@Crud({
    model: {
      type: ReportTipIssue
    }
  })
  @Controller('report-tip-issue')
  export class ReportTipIssueController implements CrudController<ReportTipIssue> {
    constructor(public service: ReportTipIssueService) {}
  }
