

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Sep 19 2023 10:34:24 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { TrailerStatus } from './trailer-status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TrailerStatusService } from './trailer-status.service';
import { TrailerStatusController } from './trailer-status.controller';

@Module({
    imports: [TypeOrmModule.forFeature([TrailerStatus])],
    providers: [TrailerStatusService],
    exports: [],
    controllers: [TrailerStatusController],
  })
  export class TrailerStatusModule {}

