
import { TrailerStatus } from "./trailer-status.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Sep 19 2023 10:34:24 GMT+0100 (British Summer Time)
 */
@Injectable()
export class TrailerStatusService extends TypeOrmCrudService<TrailerStatus> {
  constructor(@InjectRepository(TrailerStatus) repo) {
    super(repo);
  }
}
