
import { ServiceType } from "./service-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 10:37:56 GMT+0100 (British Summer Time)
 */
@Injectable()
export class ServiceTypeService extends TypeOrmCrudService<ServiceType> {
  constructor(@InjectRepository(ServiceType) repo) {
    super(repo);
  }
}
