
import { ServiceType } from "./service-type.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { ServiceTypeService } from "./service-type.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 10:37:56 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: ServiceType
    }
  })
  @Controller('service-type')
  export class ServiceTypeController implements CrudController<ServiceType> {
    constructor(public service: ServiceTypeService) {}
  }
