

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Apr 19 2021 10:37:56 GMT+0100 (British Summer Time)
 */
import { Module } from '@nestjs/common';
import { ServiceType } from './service-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ServiceTypeService } from './service-type.service';
import { ServiceTypeController } from './service-type.controller';

@Module({
    imports: [TypeOrmModule.forFeature([ServiceType])],
    providers: [ServiceTypeService],
    exports: [],
    controllers: [ServiceTypeController],
  })
  export class ServiceTypeModule {}

