

/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Dec 15 2020 10:09:19 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { DefectAssignment } from './defect-assignment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DefectAssignmentService } from './defect-assignment.service';
import { DefectAssignmentController } from './defect-assignment.controller';
import { DefectJobModule } from 'src/defect-job/defect-job.module';

@Module({
    imports: [TypeOrmModule.forFeature([DefectAssignment]), DefectJobModule],
    providers: [DefectAssignmentService],
    exports: [],
    controllers: [DefectAssignmentController],
  })
  export class DefectAssignmentModule {}

