
import { Subcontractor } from "./subcontractor.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { SubcontractorService } from "./subcontractor.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Fri Aug 14 2020 16:15:01 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: Subcontractor
    }
  })
  @Feature('subcontractor')
  @Controller('subcontractor')
  export class SubcontractorController implements CrudController<Subcontractor> {
    constructor(public service: SubcontractorService) {}
  }
