
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Jan 18 2021 10:06:58 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class Reporting {
  @PrimaryGeneratedColumn() id: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

