

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Jan 18 2021 10:06:58 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { Reporting } from './reporting.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ReportingService } from './reporting.service';
import { ReportingController } from './reporting.controller';

@Module({
    imports: [TypeOrmModule.forFeature([Reporting])],
    providers: [ReportingService],
    exports: [],
    controllers: [ReportingController],
  })
  export class ReportingModule {}

