
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Driver } from "src/driver/driver.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 09:23:58 GMT+0100 (British Summer Time)
 */
@Entity()
export class DriverHours {
  @PrimaryGeneratedColumn() id: number;

  @Column() driverId: number;
  @OneToOne(type => Driver) @JoinColumn() driver: Driver;

  @Column({type: 'date'}) date: string;
  @Column({type: 'time'}) startTime: string;
  @Column({type: 'time'}) endTime: string;
  @Column({type: 'float'}) lunchBreak: string;
  @Column({type: 'float'}) chargeableHours: number;
  @Column({type: 'text'}) notes: string;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
