
import { DriverHours } from "./driver-hours.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 09:23:58 GMT+0100 (British Summer Time)
 */
@Injectable()
export class DriverHoursService extends TypeOrmCrudService<DriverHours> {
  constructor(@InjectRepository(DriverHours) repo) {
    super(repo);
  }
}
