

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 09:23:58 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { DriverHours } from './driver-hours.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DriverHoursService } from './driver-hours.service';
import { DriverHoursController } from './driver-hours.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([DriverHours]), AuthModule],
    providers: [DriverHoursService],
    exports: [],
    controllers: [DriverHoursController],
  })
  export class DriverHoursModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('driver-hour');
    }
  }

