

/**
 * This file was generated by Four Ways Technology
 *
 * On Sat Mar 20 2021 18:56:22 GMT+0000 (Coordinated Universal Time)
 */
import { Module } from '@nestjs/common';
import { EmailLog } from './email-log.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EmailLogService } from './email-log.service';
import { EmailLogController } from './email-log.controller';

@Module({
    imports: [TypeOrmModule.forFeature([EmailLog])],
    providers: [EmailLogService],
    exports: [],
    controllers: [EmailLogController],
  })
  export class EmailLogModule {}

