
import { EmailLog } from "./email-log.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Sat Mar 20 2021 18:56:22 GMT+0000 (Coordinated Universal Time)
 */
@Injectable()
export class EmailLogService extends TypeOrmCrudService<EmailLog> {
  constructor(@InjectRepository(EmailLog) repo) {
    super(repo);
  }
}
