
import { InvoiceEmailLog } from "./invoice-email-log.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { InvoiceEmailLogService } from "./invoice-email-log.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Tue Oct 26 2021 11:58:46 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: InvoiceEmailLog
    },
    query: {
      join: {
        invoice: {
          eager: false,
        },
        "invoice.account": {
          eager: false,
        }
      }
    }
  })
  @Controller('invoice-email-log')
  export class InvoiceEmailLogController implements CrudController<InvoiceEmailLog> {
    constructor(public service: InvoiceEmailLogService) {}
  }
