
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { Order } from "src/order/order.entity";
import { OrderStatus } from "src/order-status/order-status.entity";
import { User } from "src/auth/user.entity";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:53:41 GMT+0100 (British Summer Time)
 */
@Entity()
export class OrderStatusHistory {
  @PrimaryGeneratedColumn() id: number;

  @Column() orderId: number;
  @OneToOne(type => Order) @JoinColumn() order: Order;

  @Column() orderStatusId: number;
  @OneToOne(type => OrderStatus) @JoinColumn() orderStatus: OrderStatus;

  @Column({type: 'text'}) notes: string;

  @OneToOne(type => User)
  @JoinColumn({ name: "createdBy" })
  user: User;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string; 

}    
 
