
import { OrderStatusHistory } from "./order-status-history.entity";
import { Crud, CrudController, Feature } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { OrderStatusHistoryService } from "./order-status-history.service";
/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:53:41 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: OrderStatusHistory
    },
    query: {
      join: {
        orderStatus : {
          eager: true
        },
        user: {
          eager: true,
        }
      }
    }
  })
  @Feature('order-status-history')
  @Controller('order-status-history')
  export class OrderStatusHistoryController implements CrudController<OrderStatusHistory> {
    constructor(public service: OrderStatusHistoryService) {}
  }
