

/**
 * This file was generated by Four Ways Technology
 * 
 * On Mon Aug 10 2020 15:53:41 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { OrderStatusHistory } from './order-status-history.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { OrderStatusHistoryService } from './order-status-history.service';
import { OrderStatusHistoryController } from './order-status-history.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([OrderStatusHistory]), AuthModule],
    providers: [OrderStatusHistoryService],
    exports: [OrderStatusHistoryService],
    controllers: [OrderStatusHistoryController],
  })
  export class OrderStatusHistoryModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('order-status-history');
    }
  }

