
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
import { DriverJobStatus } from "src/driver-job-status/driver-job-status.entity";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 12:51:16 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class DriverJobStatusDetails {
  @PrimaryGeneratedColumn() id: number;

  @Column() vehicleId: number;
  @Column() driverId: number;
  @Column() jobId: number;
  @Column({type: 'date'}) date: string;
  @Column({nullable: true, type: 'time'}) time: string;

  @OneToOne(type => DriverJobStatus) @JoinColumn() driverJobStatus: DriverJobStatus;
  @Column({nullable: true}) driverJobStatusId: number;
  @Column({type: 'float', nullable: true}) gpsLat: number;
  @Column({type: 'float', nullable: true}) gpsLong: number;

  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

