
import { DriverJobStatusDetails } from "./driver-job-status-details.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverJobStatusDetailsService } from "./driver-job-status-details.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 12:51:16 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: DriverJobStatusDetails
    },
    query: {
      join: {
        DriverJobStatus: {
          eager: false,
        }
      }
    }
  })
  @Controller('driver-job-status-details')
  export class DriverJobStatusDetailsController implements CrudController<DriverJobStatusDetails> {
    constructor(public service: DriverJobStatusDetailsService) {}
  }
