
import { DriverJobStatusDetails } from "./driver-job-status-details.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Jan 15 2021 12:51:16 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class DriverJobStatusDetailsService extends TypeOrmCrudService<DriverJobStatusDetails> {
  constructor(@InjectRepository(DriverJobStatusDetails) repo) {
    super(repo);
  }

  async getAllHistoryByJobId(jobId: number) {
    if(!jobId || jobId === -1) {
      throw new Error('Jobid must be supplied in getAllHistoryByPodId');
    }

    return await this.find({
      where: {
        jobId: jobId,
      }
    });
  }
}
