
import { RecurrenceType } from "./recurrence-type.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Feb 25 2021 17:57:35 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class RecurrenceTypeService extends TypeOrmCrudService<RecurrenceType> {
  constructor(@InjectRepository(RecurrenceType) repo) {
    super(repo);
  }
}
