
import { DriverCheckReports } from "./driver-check-reports.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Injectable()
export class DriverCheckReportsService extends TypeOrmCrudService<DriverCheckReports> {
  constructor(@InjectRepository(DriverCheckReports) repo) {
    super(repo);
  }
}
