
import { DriverCheckReports } from "./driver-check-reports.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { DriverCheckReportsService } from "./driver-check-reports.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Fri Aug 07 2020 21:32:36 GMT+0100 (British Summer Time)
 */
@Crud({
    model: {
      type: DriverCheckReports
    },
    query:{
      join:{
        vehicleCheck:{
          eager:true
        },
        reportStatus:{
          eager:true
        },
        vehicle:{
          eager:true
        },
        driver:{
          eager:true
        },
      }
    }
  })
  @Controller('driver-check-reports')
  export class DriverCheckReportsController implements CrudController<DriverCheckReports> {
    constructor(public service: DriverCheckReportsService) {}
  }
