
import { Fitter } from "src/fitter/fitter.entity";
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, OneToOne, JoinColumn } from "typeorm";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 10:52:59 GMT+0000 (Greenwich Mean Time)
 */
@Entity()
export class FitterHours {
  @PrimaryGeneratedColumn() id: number;


  @Column() fitterId: number;
  @OneToOne(type => Fitter) @JoinColumn() fitter: Fitter;

  @Column({type: 'date'}) date: string;
  @Column({type: 'time'}) startTime: string;
  @Column({type: 'time'}) endTime: string;
  @Column({type: 'float'}) lunchBreak: string;
  @Column({type: 'float'}) chargeableHours: number;
  @Column({type: 'text'}) notes: string;

  @Column() createdBy: number;
  @CreateDateColumn() createdAt: string;
  @UpdateDateColumn() updatedAt: string;

}

