
import { FitterHours } from "./fitter-hours.entity";
import { Crud, CrudController } from "@nestjsx/crud";
import { Controller } from "@nestjs/common";
import { FitterHoursService } from "./fitter-hours.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 10:52:59 GMT+0000 (Greenwich Mean Time)
 */
@Crud({
    model: {
      type: FitterHours
    },
    query: {
      join: {
        fitter: {
          eager: true,
        }
      }
    }
  })
  @Controller('fitter-hours')
  export class FitterHoursController implements CrudController<FitterHours> {
    constructor(public service: FitterHoursService) {}
  }
