
import { FitterHours } from "./fitter-hours.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Mon Mar 15 2021 10:52:59 GMT+0000 (Greenwich Mean Time)
 */
@Injectable()
export class FitterHoursService extends TypeOrmCrudService<FitterHours> {
  constructor(@InjectRepository(FitterHours) repo) {
    super(repo);
  }
}
