

/**
 * This file was generated by Four Ways Technology
 * 
 * On Tue Aug 11 2020 12:14:24 GMT+0100 (British Summer Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { ContainerType } from './container-type.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerTypeService } from './container-type.service';
import { ContainerTypeController } from './container-type.controller';
import { AuthMiddleware } from 'src/auth/auth.middleware';
import { AuthModule } from 'src/auth/auth.module';

@Module({
    imports: [TypeOrmModule.forFeature([ContainerType]), AuthModule],
    providers: [ContainerTypeService],
    exports: [],
    controllers: [ContainerTypeController],
  })
  export class ContainerTypeModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('container-type');
    }
  }

