

/**
 * This file was generated by Four Ways Technology
 *
 * On Thu Feb 04 2021 15:02:00 GMT+0000 (Greenwich Mean Time)
 */
import { Module } from '@nestjs/common';
import { ContainerGrades } from './container-grades.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContainerGradesService } from './container-grades.service';
import { ContainerGradesController } from './container-grades.controller';

@Module({
    imports: [TypeOrmModule.forFeature([ContainerGrades])],
    providers: [ContainerGradesService],
    exports: [],
    controllers: [ContainerGradesController],
  })
  export class ContainerGradesModule {}

