
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
import { Module, MiddlewareConsumer } from '@nestjs/common';
import { VehicleInspectionAssignments } from './vehicleinspectionassignments.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VehicleInspectionAssignmentsService } from './vehicleinspectionassignments.service';
import { VehicleInspectionAssignmentsController } from './vehicleinspectionassignments.controller';
import { AuthModule } from 'src/auth/auth.module';
import { AuthMiddleware } from 'src/auth/auth.middleware';

@Module({
    imports: [TypeOrmModule.forFeature([VehicleInspectionAssignments]), AuthModule],
    providers: [VehicleInspectionAssignmentsService],
    exports: [VehicleInspectionAssignmentsService],
    controllers: [VehicleInspectionAssignmentsController],
  })
  export class VehicleInspectionAssignmentsModule {
    configure(consumer: MiddlewareConsumer) {
      consumer
      .apply(AuthMiddleware)
      .forRoutes('vehicleinspectionassignments');
    }
  }
