
import { VehicleInspectionAssignments } from "./vehicleinspectionassignments.entity";
import { Crud, CrudController, Feature, Action } from "@nestjsx/crud";
import { Controller, Delete, Param } from "@nestjs/common";
import { VehicleInspectionAssignmentsService } from "./vehicleinspectionassignments.service";
/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
@Crud({
    model: {
      type: VehicleInspectionAssignments
    },
    query: {
      join: {
        vehicleInspectionInterval:{
          eager:true
        },
      }
    }
  })
  @Controller('vehicleinspectionassignments')
  @Feature('vehicleinspectionassignments')
  export class VehicleInspectionAssignmentsController implements CrudController<VehicleInspectionAssignments> {
    constructor(public service: VehicleInspectionAssignmentsService) {}

    @Action('deleteByParentId')
    @Delete('deleteByParentId/:parentId')
    deleteByParentId(@Param() params) {

      if(!params['parentId']) {
        throw new Error('You must supply an id for deleteByParentId');
      }

      this.service.deleteByParentId(params['parentId']);
      return [];
    }
  }
