
import { VehicleInspectionAssignments } from "./vehicleinspectionassignments.entity";
import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";

import { TypeOrmCrudService } from "@nestjsx/crud-typeorm";

/**
 * This file was generated by Four Ways Technology
 *
 * On Wed Nov 25 2020 10:23:21 GMT (British Winter Time)
 */
@Injectable()
export class VehicleInspectionAssignmentsService extends TypeOrmCrudService<VehicleInspectionAssignments> {
  constructor(@InjectRepository(VehicleInspectionAssignments) repo) {
    super(repo);
  }

  public async createDTO(dto: any) {
    return await this.repo.save(dto);
  }

  async deleteByParentId(parentId){
    if(!parentId || parentId <= -1) {
      throw new Error("you must provide an valid user group id in deleteByParentId");
    }

    await this.repo.createQueryBuilder()
    .delete()
    .from(VehicleInspectionAssignments)
    .where("vehicleDetailId = :id", { id: parentId })
    .execute();
  }
}
